### ISSUE TITLE
warning: multiple different client offset_encodings detected for buffer, this is not supported yet

### ISSUE THREAD

**Issue by kylo252** [jose-elias-alvarez/null-ls.nvim#428] opened 2021-12-13 17:49 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.7.0-dev+717-gf37c5f180

### null-ls config

```lua
require("null-ls").setup({
    sources = {
        require("null-ls").builtins.code_actions.gitsigns,
    },
})
```

### Steps to reproduce

This validation is introduced in https://github.com/neovim/neovim/pull/16382

You need to have `clangd` which [sets an offset encoding by default](https://github.com/neovim/nvim-lspconfig/blob/c37bf4a2e87df0da5895402b01b427442e0633ff/lua/lspconfig/server_configurations/clangd.lua#L35), running and then any source that attaches to the same buffer.

### Expected behavior

NA

### Actual behavior

NA

### Debug log

NA

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Not really sure how we can get around this. I thought It's probably sufficient to set the same encoding value as `clangd` but that didn't seem to fix it.

```diff
diff --git a/lua/null-ls/rpc.lua b/lua/null-ls/rpc.lua
index 9e45c0a..e9efa6d 100644
--- a/lua/null-ls/rpc.lua
+++ b/lua/null-ls/rpc.lua
@@ -44,6 +44,7 @@ local capabilities = {
         openClose = true,
         save = true,
     },
+    offsetEncoding = { "utf-8", "utf-16" },
 }
 
 M.capabilities = capabilities
```

I also have no idea if there are any downsides to that.

**Comment by jose-elias-alvarez** [comment] 2021-12-13 18:23
So we can set `client.offset_encoding` by passing it into the `vim.lsp.start_client` options:

```diff
diff --git a/lua/null-ls/client.lua b/lua/null-ls/client.lua
index a49aebc..24ada84 100644
--- a/lua/null-ls/client.lua
+++ b/lua/null-ls/client.lua
@@ -69,6 +69,7 @@ M.start_client = function(fname)
                 )
             end
         end),
+        offset_encoding = "utf-8",
     }

     log:trace("starting null-ls client")
```

This fixes the warning when using `clangd` but creates the same issues for servers using `utf-16`. Changing this also immediately breaks formatting and probably has other side effects.

I'm actually not sure how `clangd` handles setting `offsetEncoding` via `capabilities`. [This docstring](https://github.com/neovim/neovim/blob/f37c5f180a12d0f3a36a8f10ca6719c6f1eb0d49/runtime/lua/vim/lsp.lua#L657) hints that it's doing something special in `on_init`, but I don't know where.

If I understand correctly, this is a legitimate warning that would also be triggered when using 2 actual LSP servers with different offset encodings, right? I'm not sure if there's anything we can do about this until multiple offset encodings are supported (apart from maybe reducing the frequency of the warning, since it's pretty aggressive).

**Comment by mjlbach** [comment] 2021-12-13 18:30
FYI we didn't use to support mixed offsetEncodings, it used to send the wrong ranges (always utf-16). We changed it to send the correct ranges but with the limitation that it *only* supports a single offset encoding per buffer. All clients attached to a given buffer must have the same client.offset_encoding (capability only indicates to the language server what our client supports). I assume the issue for null-ls is that there cannot be "groups" of null-ls clients with different offset encodings.

**Comment by kylo252** [comment] 2021-12-13 18:39
I was doing some testing and here are the results.

Changing the settings in https://github.com/neovim/nvim-lspconfig/blob/c37bf4a2e87df0da5895402b01b427442e0633ff/lua/lspconfig/server_configurations/clangd.lua

```lua
-- results in 'utf-8'
offsetEncoding = { 'utf-8', 'utf-16' },

 -- results in 'utf-16', probably wrong syntax
offsetEncoding = 'utf-8',

-- results in 'utf-8' but null-ls is 'utf-16' anyway
offsetEncoding = { 'utf-8' },
```

Doing the same change for null-ls doesn't do anything, still not sure why.

```diff
diff --git a/lua/null-ls/rpc.lua b/lua/null-ls/rpc.lua
index 9e45c0a..534b03f 100644
--- a/lua/null-ls/rpc.lua
+++ b/lua/null-ls/rpc.lua
@@ -44,6 +44,7 @@ local capabilities = {
         openClose = true,
         save = true,
     },
+    offsetEncoding = { "utf-8" }, -- this doesn't do anything, null-ls always uses utf-16
 }
 
 M.capabilities = capabilities
```

**Comment by jose-elias-alvarez** [comment] 2021-12-13 19:07
> FYI we didn't use to support mixed offsetEncodings, it used to send the wrong ranges (always utf-16). We changed it to send the correct ranges but with the limitation that it _only_ supports a single offset encoding per buffer. All clients attached to a given buffer must have the same client.offset_encoding (capability only indicates to the language server what our client supports). I assume the issue for null-ls is that there cannot be "groups" of null-ls clients with different offset encodings.

Thanks for the info, this makes sense. The warning should only pop up in the presence of a different client, since all null-ls clients (and there should only be one unless something went wrong) will always have the same offset encoding.

@kylo252 I *think* this diff makes `utf-8` work (tests are passing, at least, and I don't immediately see any bad behavior):

```diff
diff --git a/lua/null-ls/client.lua b/lua/null-ls/client.lua
index a49aebc..97c0a3d 100644
--- a/lua/null-ls/client.lua
+++ b/lua/null-ls/client.lua
@@ -69,6 +69,7 @@ M.start_client = function(fname)
                 )
             end
         end),
+        client_encoding = "utf-8",
     }

     log:trace("starting null-ls client")
diff --git a/lua/null-ls/diff.lua b/lua/null-ls/diff.lua
index 20e3dab..311524f 100644
--- a/lua/null-ls/diff.lua
+++ b/lua/null-ls/diff.lua
@@ -140,8 +140,8 @@ function M.compute_diff(old_lines, new_lines, line_ending)
         adj_end_char = #old_lines[#old_lines + end_line + 1] + end_char + 1
     end

-    _, start_char = vim.str_utfindex(old_lines[start_line], start_char - 1)
-    _, end_char = vim.str_utfindex(old_lines[#old_lines + end_line + 1], adj_end_char)
+    start_char = start_char - 1
+    end_char = adj_end_char

     local result = {
         range = {
```

The issue is then that we get the same warning with `utf-16` clients. Given that mixing client offset encodings is a legitimate issue, I don't really know if there's a good solution until that situation is handled upstream (which at a glance seems like a real challenge).

**Comment by levouh** [comment] 2021-12-18 16:29
For visibility as a discussion per [here](https://github.com/neovim/neovim/pull/16694), an interim "solution" (at least to get rid of the warning that happens on every key press in insert mode) is to do what is mentioned there:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.offsetEncoding = { "utf-16" }
require("lspconfig").clangd.setup({capabilities = capabilities})
```

and all seems to still work as normal. I run `clangd` + use `clang-format` from `null-ls` and have not had any issues.

**Comment by kylo252** [comment] 2021-12-18 17:14
> I run `clangd` + use `clang-format` from `null-ls` and have not had any issues.

Just a heads-up, `clangd` can already use `clang-format` natively, so there's no need to invoke `null-ls`.

**Comment by jose-elias-alvarez** [comment] 2021-12-18 17:28
> For visibility from a discussion [here](https://github.com/neovim/neovim/pull/16694), an interim "solution" (at least to get rid of the warning that happens on every key press in insert mode) is to do what is mentioned there:
> 
> ```lua
> local capabilities = vim.lsp.protocol.make_client_capabilities()
> capabilities.offsetEncoding = { "utf-16" }
> require("lspconfig").clangd.setup({ capabilities = capabilities })
> ```
> 
> and all seems to still work as normal. I run `clangd` + use `clang-format` from `null-ls` and have not had any issues. This "works" because the [default assumed encoding](https://github.com/neovim/neovim/blob/ff1b0f632a8d3aed0ba861057e7bd8ade4540277/runtime/lua/vim/lsp/util.lua#L1771) (as `null-ls` provides none) is `utf-16`.

Thanks for the workaround! I'll pin the issue for now.

**Comment by Chaitanyabsprip** [comment] 2022-01-19 16:24
I haven't even mentioned c filetype in null-ls config, still it attaches to the buffer for some reason.

**Comment by jose-elias-alvarez** [comment] 2022-01-19 16:52
@Chaitanyabsprip From your dotfiles, it looks like you are using the `gitsigns` built-in, which is active for all filetypes by default. You can [configure filetypes](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#filetypes) for that built-in or use one of the workarounds mentioned here. 

Ideally, null-ls wouldn't receive `textDocument/didChange` notifications at all without a diagnostics source registered, which would avoid your issue, but it's not possible with the current architecture. Eventually I want null-ls to independently register itself for change events, but that'll take time and work.

**Comment by pgherveou** [comment] 2022-01-20 09:02
👋  there, I am also running into this
I am using the ccls client and clang_format through null-ls for formatting
I used capabilities.offsetEncoding = { "utf-16" } when configuring ccls, but I am seeing the warning.

Is there an easy way to debug this?

**Comment by sanfusu** [comment] 2022-01-28 17:07
https://github.com/neovim/neovim/blob/b455e0179b4288c69e6231bfcf8d1c132b78f2fc/runtime/lua/vim/lsp/util.lua#L1812

**Comment by sanfusu** [comment] 2022-01-28 17:22
Just some relevant information

https://github.com/neovim/neovim/blob/b455e0179b4288c69e6231bfcf8d1c132b78f2fc/runtime/lua/vim/lsp/util.lua#L1812

**Comment by ybisland** [comment] 2022-05-04 05:15
Even though I used `capabilities.offsetEncoding = { "utf-16" }`, I also see this warning when using `clangd` lsp and `cppcheck` through null-ls for diagnostics.

**Neovim Version:**
NVIM v0.7.0                                                                                                                                                  
Build type: Release

**null-ls config:**
```
require("null-ls").setup({
    sources = {
        require("null-ls").builtins.diagnostics.cppcheck,
    },
})
```

**Comment by kylo252** [comment] 2022-05-07 08:40
> Even though I used `capabilities.offsetEncoding = { "utf-16" }`, I also see this warning when using `clangd` lsp and `cppcheck` through null-ls for diagnostics.

are you adding the setting to `clangd` or `null-ls`? since it's a command-line flag, it should show up as part of the `clangd` command in `:LspInfo`
![image](https://user-images.githubusercontent.com/59826753/167243490-5b3d9400-b5cb-41e3-9354-1d456ee0851f.png)

**Comment by shunlir** [comment] 2022-05-08 11:39
Is it possible to make `null-ls's` offsetEncoding configurable? `ccls` only supports utf-32, this means the two lsp clients have different offset_encoding, and have the warning.

**Comment by jose-elias-alvarez** [comment] 2022-05-08 17:58
> Is it possible to make `null-ls's` offsetEncoding configurable? `ccls` only supports utf-32, this means the two lsp clients have different offset_encoding, and have the warning. https://github.com/MaskRay/ccls/blob/master/src/messages/initialize.cc#L229

It is configurable for null-ls in the same way it's configurable for any other client.

I'm going to update the OP with a workaround and close this issue, since it is not specific to null-ls (you can easily replicate it by attaching 2 LSP clients with different offset encoding to a single buffer).

**Closed by jose-elias-alvarez** 2022-05-08 17:58 UTC
Labels: bug

**Comment by shunlir** [comment] 2022-05-09 02:46
I found a simple way to config `null-ls` to use any `offsetEncoding`.
(It works together with clangd which is configured utf-32, to align with ccls which only supports utf-32)
```
return function()
  require("null-ls").setup({
    on_init = function(new_client, _) 
      new_client.offset_encoding = 'utf-32'
    end,
  })
end
```
Given null-ls has some shortcuts for its client/server interaction, it's not required to do the offsetEncoding negotiation, for which the details, see `help  vim.lsp.start_client` on_init about how offsetEncoding/offset_encoding should work.
