### ISSUE TITLE
null-ls spawns multiple instances of the same source after format

### ISSUE THREAD

**Issue by kmoschcau** [jose-elias-alvarez/null-ls.nvim#1196] opened 2022-10-18 07:52 UTC
@kmoschcau Please put together a separate issue with a full minimal reproduction.

_Originally posted by @jose-elias-alvarez in https://github.com/jose-elias-alvarez/null-ls.nvim/issues/596#issuecomment-1281084560_

Null-ls seems to spawn multiple linting processes after formatting. I created a private minimal production repro repo and sent and invite to @jose-elias-alvarez. It is private since it contains code from my workplace. I will add instructions momentarily.

---

I added a readme to the repo. Here is an excerpt of the readme for public reproduction:
```markdown
# A minimal reproduction of null-ls spawning multiple instances of sources

## Environment Note

All of these tests were done on a WSL2 instance (Ubuntu 20.04) on Windows 10
(21H2 Build 19044.2130). Might have something to do with it, might not.

## Java code file

I can not freely share the file under test, as it is proprietary code. However I
think an sufficiently large java file should work as well. The original file
had around 700 lines.

## Setup

First check the `checkstyle`, `pmd` and `google-java-format` files. These need
to point to the install location of their respective tools, then be added to the
PATH.

Downloads:
- [checkstyle](https://github.com/checkstyle/checkstyle/releases/)
- [pmd](https://github.com/pmd/pmd/releases)
- [google-java-format](https://github.com/google/google-java-format/releases)

On the nvim side, the null-ls plugin is expected to be in the runtime path.

## Reproduction

Have for example `htop` open and observe processes started.

### With minimal config

Run `nvim -u minimal-config.lua SomeClass.java`, then press `<space>f` in
normal mode. Observe that multiple instances of pmd and checkstyle are started.

Side note: I notice that formatting seems to be a two step process here, because
I can see an intermediate state of the file before the final formatted state is
reached. I have no idea how that happens, because `google-java-format` is the
only registered formatter according to `:NullLsInfo`.

### With full config

With the minimal config I couldn't get it into a state of basically infinitely
spawning new processes, but I can do it after one or two tries with my [own
config](https://github.com/kmoschcau/nvim-config).

Check out the config above and replace your own with that one. Then start nvim,
run the following:
- `:lua require "plugins"`
- `:PackerSync`

Quit, then run `nvim SomeClass.java` and try the same `<space>f` as
before. If that doesn't cause the spawn, write the file and repeat until it
does. Usually for me it happens on the second try. I then have to kill this nvim
instance to stop the spawning and not choke my machine.
```

If needed, I can also share the rest of the files (config and tool executables)
apart from the code file for others later.

**Comment by kmoschcau** [comment] 2022-10-18 11:15
I figured out why I saw the intermediate formatting step: jdtls also still had formatting enabled.

**Comment by kmoschcau** [comment] 2022-10-18 16:01
OK so it does indeed seem to have been either jdtls on its own or in combination with google-java-format. I have no idea if using `{ async = true }` on the formatting call played into this, causing the two to write to the same buffer/file at the same time. But it doesn't seem to happen anymore. @jose-elias-alvarez you can close this if you no longer need it.

**Comment by jose-elias-alvarez** [comment] 2022-10-18 16:22
Thanks for putting this together, I can see how async formatting with another language server could cause issues (especially since language servers are able to return separate edits, each of which would trigger another `didChange` notification). I imagine the takeaway here is "don't use multiple language servers for formatting" but I will take a more detailed look when I can.

**Comment by kmoschcau** [comment] 2022-11-14 06:52
@hem-brahmbhatt did you see the last two comments? You should probably disable the formatting on tsserver and only use eslint for formatting.

**Comment by jose-elias-alvarez** [comment] 2022-12-10 20:39
Closing this as I believe the issue is solved. Using multiple actual language servers for formatting will result in strange results, so I don't think there's anything we can do here apart from clarifying that this is not recommended.

**Closed by jose-elias-alvarez** 2022-12-10 20:39 UTC
