### ISSUE TITLE
Black not formatting specific file

### ISSUE THREAD

**Issue by ram02z** [jose-elias-alvarez/null-ls.nvim#700] opened 2022-02-21 19:58 UTC
### Neovim version: 
g726ec7fb1

### Black version:
22.1.0 

### OS: 
Linux

### null-ls.nvim config:
```lua
local null_ls = require("null-ls")

-- register any number of sources simultaneously
local sources = {
    null_ls.builtins.formatting.prettier,
    null_ls.builtins.formatting.black,
    null_ls.builtins.formatting.isort,
    null_ls.builtins.formatting.fish_indent,
    null_ls.builtins.formatting.stylua,
    null_ls.builtins.diagnostics.flake8.with({
        diagnostics_format = "[#{c}] #{m}",
        method = null_ls.methods.DIAGNOSTICS_ON_SAVE,
        extra_args = { "--extend-ignore", "E203", "--max-line-length", "88" }
    }),
    null_ls.builtins.code_actions.gitrebase,
}

null_ls.setup({ sources = sources, on_attach = on_attach })
```

### null-ls trace
```
[TRACE Mon 21 Feb 2022 19:28:06 GMT] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method textDocument/formatting
[TRACE Mon 21 Feb 2022 19:28:06 GMT] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG Mon 21 Feb 2022 19:28:06 GMT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:335: spawning command [black] at /home/omar/psyoz1/local/team20_project with args { "--stdin-filename", "/home/omar/psyoz1/local/team20_project/backend/app/parser.py", "--quiet", "-" }
[TRACE Mon 21 Feb 2022 19:28:06 GMT] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
```

Black formatting isn't working on a specific file. Its strange because it has stopped working on a specifc file but works fine on a smaller file in the same directory. Running black directly from the terminal does format the file just fine. I have been working on this file regularly and black formatting with null ls has been working fine until today, Rolling back to a previous neovim nightly doesn't fix the issue either.

_Originally posted by @ram02z in https://github.com/jose-elias-alvarez/null-ls.nvim/issues/640#issuecomment-1047175590_

**Comment by jose-elias-alvarez** [comment] 2022-02-21 22:43
Can you replicate the issue using a full minimal config?

> Download the minimal config using curl -fLO https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua. Edit it to include the configuration necessary to reproduce your bug and paste it here.

**Comment by ram02z** [comment] 2022-02-24 16:57
Sorry, I am going to be busy for a few weeks. I will try to test using a minimal config when I can.

**Comment by karljs** [comment] 2022-03-06 19:26
@jose-elias-alvarez I was able to reproduce this by simply adding the single line `null_ls.builtins.formatting.black` into the `sources` definition in the minimal configuration, and then trying to run `:lua vim.lsp.buf.formatting()` on a Python file.

I see in the logs that `null-ls` is running black with no error output (see below) but the file is not reformattted.  If I run black directly in the same instance of nvim with `! black mypythonfile.py`, it reformats as expected.

```
[TRACE Sun Mar  6 11:23:22 2022] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method textDocument/formatting
[TRACE Sun Mar  6 11:23:22 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_FORMATTING
[DEBUG Sun Mar  6 11:23:22 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:341: spawning command "black" at /Users/karl/everycheese with args { "--stdin-filename", "/Users/karl/everycheese/everycheese/users/views.py", "--quiet", "-" }
[TRACE Sun Mar  6 11:23:23 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
[TRACE Sun Mar  6 11:23:23 2022] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:225: output: nil
```

**Comment by jose-elias-alvarez** [comment] 2022-03-06 19:42
@karljs With [this minimal config](https://gist.github.com/jose-elias-alvarez/e476d6bfc9847262d41a2058ce7a88c6), I am successfully able to run `black` on the following random example I found on Google when calling `vim.lsp.buf.formatting_sync()`:

```python
def is_unique(
               s
               ):
    s = list(s
                )
    s.sort()
 
 
    for i in range(len(s) - 1):
        if s[i] == s[i + 1]:
            return 0
    else:
        return 1
 
 
if __name__ == "__main__":
    print(
          is_unique(input())
         )
```

For context, `black --version` outputs `black, 22.1.0 (compiled: yes)`, and this works for me on both the latest Neovim master and 0.6.1. 

Also, calling `!black %` from within Neovim isn't the same, since the argument structure is different and it runs directly on the file. What do you see when you run this from the command line?

```sh
cat views.py | black --stdin-filename views.py --quiet -
```

**Comment by karljs** [comment] 2022-03-06 19:46
I have some new clues.  If I create a minimal example with Poetry, via something like:
```
poetry init
poetry add --dev black
nvim junk.py
```

Put some mediocre formatting into the file, e.g.:

```
def junk(a, b):
    return  a+ b
```

And run `:lua vim.lsp.buf.formatting_sync()`, which does not reformat.

If I produce the same virtual environment via:
```
python -m venv myenv
source myenv/bin/activate
nvim junk.py`

and then follow the same steps, it _does_ work

**Comment by jose-elias-alvarez** [comment] 2022-03-06 19:55
I'm not familiar with `poetry`, but if you are setting up `black` via some means that does not add it to `$PATH` in a way that persists through new shells / processes, you will run into issues and will need to work around them for projects using that structure. 

If you are successfully able to run `black` using the *exact command and arguments* I mentioned above from the command line, that's potentially a null-ls issue. In that case, I could try to help if you're able to provide an independent reproduction project (one that doesn't depend on external tools), but the Python ecosystem is too large to support every potential project structure out of the box.

**Comment by karljs** [comment] 2022-03-06 20:05
That makes sense, it sounds like maybe my issues are driven by something unique to Poetry, which I'll have to investigate when I get a little extra time.

Sorry to derail this if it turns out my issue was unrelated, but thanks for being so quick to jump in on potential bugs!

**Comment by jose-elias-alvarez** [comment] 2022-05-15 17:46
Closing this since I don't have the information needed to investigate, but feel free to open a new issue if you're still having the issue and have the time to put together a minimal reproduction.

**Closed by jose-elias-alvarez** 2022-05-15 17:46 UTC

**Comment by luisiacc** [comment] 2022-06-16 06:53
> That makes sense, it sounds like maybe my issues are driven by something unique to Poetry, which I'll have to investigate when I get a little extra time. 

I'm having this exact problem, using a poetry env, but only happens on big files(more than 7000 lines), it says it times out, but it doesn't even wait the default 5 seconds, it just times out very quickly.

**Comment by luisiacc** [comment] 2022-06-16 16:56
@jose-elias-alvarez  I found a minimal repro file, using this as you said does format the file correctly:
`cat lists_api.py | black --stdin-filename lists_api.py --quiet - > newfile.py`

But when doing it from the editor it times out really fast, not waiting the default 5 seconds, I even incremented the default timeout to 10 secs, but got the same result.

Set up is like this:
```lua
local null_ls = require("null-ls")
local fmt = null_ls.builtins.formatting
null_ls.setup({
  autostart = true,
  default_timeout = 10000,
  sources = {
    fmt.black.with({
      -- prefer_local = ".venv/bin",
      args = { "--quiet", "-" },
      extra_args = { "--line-length", "120" },
    })
  }
})

```

This is the file 
[lists_api.zip](https://github.com/jose-elias-alvarez/null-ls.nvim/files/8920896/lists_api.zip)

**Comment by luisiacc** [comment] 2022-06-16 17:06
yes
