### ISSUE TITLE
Cannot use null-ls with the latest `neovim/nvim-lspconfig`

### ISSUE THREAD

**Issue by captainko** [jose-elias-alvarez/null-ls.nvim#378] opened 2021-11-26 14:20 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

  NVIM v0.6.0-dev+634-geb876a0a6 

### null-ls config

```lua
null_ls.config {
	debug = true,
	sources = {...}
}
lspconfig["null-ls"].setup { ... }
```

### Steps to reproduce

Run require('lspconfig')['null-ls'].setup {...}

### Debug log

```
Cannot access configuration for null-ls. Ensure this server is listed in `server_configurations.md` or added as a custom server.
packer.nvim: Error running config for null-ls.nvim: ...pack/packer/start/null-ls.nvim/lua/null-ls/lspconfig.lua:100: attempt to index field 'manager' (a nil value)
```

### Help

No

**Comment by mjlbach** [comment] 2021-11-26 14:22
Relevant lines of code for indexing the `lspconfig` table are here: https://github.com/neovim/nvim-lspconfig/blob/b2d302f1609a8267f4b855d8853fba65669aa8e5/lua/lspconfig.lua#L72-L85

**Comment by numToStr** [comment] 2021-11-26 15:39
So, the issue might be related to [rpc.lua](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/e76aefca283032e1d85a8e3094531124ff8172d3/lua/null-ls/rpc.lua#L56) looking for `null-ls` even before [registering](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/e76aefca283032e1d85a8e3094531124ff8172d3/lua/null-ls/init.lua#L31) itself.

**Comment by jose-elias-alvarez** [comment] 2021-11-26 15:59
@numToStr Thanks for looking into this, I’m with my family and away from my computer for the weekend so I can’t fix this directly. Does switching the order of the lines in init.lua make a difference? 

If the changes mean that the index metamethod shows an error message if the server is not yet configured, we either need to manually track whether the server has been configured or use a different method to access the config object. Reverting the rpc changes in 4e9e786e7621dcbe0c3d8d473fc434a2a2d2687b may also help.

**Comment by mjlbach** [comment] 2021-11-26 16:00
you should be able to just directly index require('lspconfig').configs to avoid the issue, should be a one line change

**Comment by jose-elias-alvarez** [comment] 2021-11-26 16:07
@mjlbach Thank you! 

If someone having this issue could put together a quick PR changing instances of `require("lspconfig")["null-ls"]` to `require("lspconfig").configs["null-ls"]` and verify that it works, it would be a big help.

**Comment by jose-elias-alvarez** [comment] 2021-11-26 17:07
The linked PR seems to have introduced some issues. This may require some additional work to solve completely, so if this is breaking your workflow please pin lspconfig to `10ad0cca1b83713ed98ed4cb7ea60f2ea8e55c49` until we can get it solved.

**Comment by jose-elias-alvarez** [comment] 2021-11-26 18:00
b07ce47f02c7b12ad65bfb4da215c6380228a959 should fix the core indexing issue. Can anyone else having the issue update null-ls and see if everything works for now?

**Comment by gadkadosh** [comment] 2021-11-26 18:03
Works for me now!

**Comment by vinnyA3** [comment] 2021-11-26 18:04
@jose-elias-alvarez just updated `null-ls` and unlocked my `nvim-lspconfig` version.  Everything works!  No error output on startup

**Comment by briones-gabriel** [comment] 2021-11-26 18:06
I've updated the plugin, it seems to work now!

**Comment by jose-elias-alvarez** [comment] 2021-11-26 18:12
Great, thanks everyone for confirming. Will close this for now and investigate potential regressions when I can.

**Closed by jose-elias-alvarez** 2021-11-26 18:12 UTC
Labels: bug
