### ISSUE TITLE
eslint file path rule not working

### ISSUE THREAD

**Issue by hesxenon** [jose-elias-alvarez/null-ls.nvim#1042] opened 2022-08-24 10:56 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.7.2

### Operating System

EndeavourOS

### Minimal config

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = {
          null_ls.builtins.diagnostics.eslint,
        },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

- clone `git@gitlab.com:hesxenon/null-ls-bug-repro.git`
- checkout `eslint-plugin-import/no-restricted-paths`
- run `npm ci`
- run `nvim --clean -u minimal_init.lua client/application/foo.js`

### Expected behavior

the import should cause an error since it's blacklisted

### Actual behavior

no error is displayed

### Debug log

```
[TRACE Mi 24 Aug 2022 12:48:57] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method shutdown
[TRACE Mi 24 Aug 2022 12:48:57] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method exit
[TRACE Mi 24 Aug 2022 12:48:58] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:106: starting null-ls client
[TRACE Mi 24 Aug 2022 12:48:58] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:121: received LSP request for method initialize
[DEBUG Mi 24 Aug 2022 12:48:58] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:161: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/hesxenon/projects/test/client/application/foo.js"
  }
}
[TRACE Mi 24 Aug 2022 12:48:58] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method initialized
[TRACE Mi 24 Aug 2022 12:48:58] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:146: received LSP notification for method textDocument/didOpen
[TRACE Mi 24 Aug 2022 12:48:58] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Mi 24 Aug 2022 12:48:58] ...rt/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:35: attempting to find local executable node_modules/.bin/eslint_d
[TRACE Mi 24 Aug 2022 12:48:58] ...rt/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:39: resolved dynamic command for [node_modules/.bin/eslint_d] with cwd=/home/hesxenon/projects/test
[DEBUG Mi 24 Aug 2022 12:48:58] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:286: Using dynamic command for [eslint_d], got: "/home/hesxenon/projects/test/node_modules/.bin/eslint_d"
[DEBUG Mi 24 Aug 2022 12:48:58] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:346: spawning command "/home/hesxenon/projects/test/node_modules/.bin/eslint_d" at /home/hesxenon/projects/test/client with args { "-f", "json", "--stdin", "--stdin-filename", "/home/hesxenon/projects/test/client/application/foo.js", "--ext", ".ts" }
[TRACE Mi 24 Aug 2022 12:48:58] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:217: error output: nil
[TRACE Mi 24 Aug 2022 12:48:58] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:218: output: [{"filePath":"/home/hesxenon/projects/test/client/application/foo.js","messages":[],"suppressedMessages":[],"errorCount":0,"fatalErrorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
[TRACE Mi 24 Aug 2022 12:48:58] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:169: received diagnostics from source 1
[TRACE Mi 24 Aug 2022 12:48:58] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:170: {}
```

### Help

No

#### Additional Context

From the log you can see that eslint_d is spawned in the wrong directory; reproducing this actually took me a while and the erroneous behaviour only started after I had created a npm workspace.

My guess is that the eslint_d source is looking for the nearest package.json to the determine the project root and _then_ the nearest eslint config to determine which rules to use. I infer this because rules that are not specific to paths seem to work without a problem.

Running `cd client && npx eslint application/foo.js` seems to confirm this.

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment] 2022-09-02 15:45
Maybe I'm missing something but I can't seem to clone the reproduction repository? Theoretically the command's `cwd` is set from [the nearest ESLint config file](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/14ec7646ed808b080d3f4e2e3bd7ba0bc1fe1dfd/lua/null-ls/builtins/diagnostics/eslint.lua#L47), though there might be a bad interaction here. If you can tell me how to access the repository I'm happy to take a closer look.

**Comment by hesxenon** [comment] 2022-09-04 15:55
I may or may not have accidentally set the repro repo to private, sorry about that.

**Comment by jose-elias-alvarez** [comment] 2022-09-04 21:32
Great, I got it working now and identified the issue. Basically, we use [these patterns](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/8ab5b579828693bb4dc206db34de51238dbd9d84/lua/null-ls/builtins/formatting/eslint.lua#L48) to resolve the closest ESLint config and use that as the `cwd` for the process. `package.json` is included since it according to [the documentation](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-file-formats) can theoretically contain an `eslintConfig` property. That's why it uses `client` as the `cwd` in your example project.

I don't know if there's a great general solution here. The best would be to actually check each `package.json` file to see if it contains the relevant property, but that adds complexity and could affect performance. A simple workaround for your case would be to just override `cwd` and remove the pattern:

```lua
local h = require("null-ls.helpers")
local u = require("null-ls.utils")

local eslint = require("null-ls").builtins.diagnostics.eslint.with({
    cwd = h.cache.by_bufnr(function(params)
        return u.root_pattern(
            ".eslintrc",
            ".eslintrc.js",
            ".eslintrc.cjs",
            ".eslintrc.yaml",
            ".eslintrc.yml",
            ".eslintrc.json"
        )(params.bufname)
    end),
})
```

**Comment by b0o** [comment] 2022-09-13 23:18
This may be happening because the user is using the [new `eslint.config.js` configuration file](https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new).

**Comment by jose-elias-alvarez** [comment] 2022-09-17 23:32
Going to close this as I believe there is an acceptable workaround and solving it definitively would require a good deal of work / complexity (though anyone who wants to tackle it should feel free to do so).

**Closed by jose-elias-alvarez** 2022-09-17 23:32 UTC
Labels: bug

**Comment by partounian** [comment] 2022-10-12 23:04
Your suggestion also fixes my issues saying my eslint plugins/extends are missing. Thanks! 

Is it possible to apply this to eslint_d?

**Comment by jose-elias-alvarez** [comment] 2022-10-12 23:52
Yes, just replace `require("null-ls").builtins.diagnostics.eslint` with `require("null-ls").builtins.diagnostics.eslint_d`.

**Comment by partounian** [comment] 2022-10-12 23:55
I tried applying those changes, but seems like eslint_d doesn't have a cwd function like eslint. Guess it needs to be added here https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/eslint_d.lua ?

**Comment by jose-elias-alvarez** [comment] 2022-10-13 00:01
You're right that we should add a default for consistency, but overriding it using the `with` method should still work. If it doesn't, please open a separate issue.
