### ISSUE TITLE
[Bug] Changelist broken

### ISSUE THREAD

**Issue by tamago324** [jose-elias-alvarez/null-ls.nvim#10] opened 2021-06-15 12:15 UTC
- `nvim --version`: NVIM v0.5.0-dev+1384-gf2906a466
- Operating system/version: Manjaro

**Describe the bug**

When I run format, the changelist is all on the first line.

**To Reproduce**

```vim
set encoding=utf-8

filetype plugin indent on
if has('vim_starting')
  let s:pluin_manager_dir='~/.config/nvim/.plugged/vim-plug'
  execute 'set runtimepath+=' . s:pluin_manager_dir
endif
call plug#begin('~/.config/nvim/.plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'jose-elias-alvarez/null-ls.nvim'
call plug#end()

set number
set nobackup
set nowritebackup
set noswapfile
set updatecount=0
set backspace=indent,eol,start
language messages en_US.utf8

lua << EOF

local null_ls = require'null-ls'

null_ls.setup {
  on_attach = function(client)
    vim.cmd([[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]])
  end,
  sources = {
    null_ls.builtins.formatting.stylua,
  }
}

EOF
```

1. `nvim -u minivimrc -i NONE`
2. `:e sample.lua`
3. edit buffer
4. `:write` (Format)

After running format, all the lines in the changelist will be on the first line.

**Expected behavior**

I want the changelist to stay intact.

**Screenshots**

https://user-images.githubusercontent.com/16581287/122050727-b969ee00-ce1e-11eb-947a-3c0206cf758c.mp4

Thank you!

**Comment by jose-elias-alvarez** [comment] 2021-06-16 04:29
Thanks again for the detailed description and reproduction. Like #9, this bug is also caused by `vim.lsp.buf.formatting`, but unfortunately I'm not sure if there's anything we can do about this one. It's possible to get the changelist for the current buffer with `vim.fn.getchangelist()`, but as far as I know there's no way to programmatically set / modify the changelist, and doing so might mess with `shada`. I've tried avoiding `vim.lsp.buf.formatting` and directly using `nvim_buf_set_text` instead, but that still clobbered the changelist.

Since this is an issue with all LSP formatting, not just null-ls, I think the fundamental fix is for Neovim to improve or add a mechanism to replace buffer content without messing up the changelist. null-ls already enhances LSP formatting, so I'd be happy to put in a workaround, but I don't know if one exists.

**Comment by tamago324** [comment] 2021-06-16 11:21
Hmmm. This is a very difficult issue.
It may be inevitable that the changelist will be broken after the formatting.
I'll let you know if I come up with a better idea.

**Comment by jose-elias-alvarez** [comment] 2021-06-17 03:50
Let me know if you come up with anything! I'll investigate other formatters and see if any of them have figured out how to avoid this issue. I know that [Neoformat](https://github.com/sbdchd/neoformat) uses `setline`, which behaves a little better but is slower and still doesn't preserve the changelist.

**Comment by jose-elias-alvarez** [comment] 2021-07-08 05:53
Small update: previously, null-ls formatting replaced the entire content of the buffer, which also wiped out the changelist for the entire document. In 512f152e3e67de7107e5884a653850880b2e9cc5, I updated formatting to only update the parts of the document that have changed, meaning that changes for lines that have not been formatted are preserved. 

This still isn't ideal, in my opinion, but it's an improvement, and until Neovim implements a less destructive mechanism for changing content, I think this is as good as it'll get.

**Comment by jose-elias-alvarez** [comment] 2021-07-17 09:55
Going to close this for now, since I think there's nothing additional we can do here, but let me know if you run into any other issues or have any ideas on how we might solve this.

**Closed by jose-elias-alvarez** 2021-07-17 09:55 UTC

**Comment by tamago324** [comment] 2021-07-18 06:35
Sorry for the late reply!
No problem with the close.
Thanks for the support.
