### ISSUE TITLE
null-ls breaks `gq` for diagnostics only providers

### ISSUE THREAD

**Issue by cryptomilk** [jose-elias-alvarez/null-ls.nvim#1431] opened 2023-03-04 14:27 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.3

### Dev Version?

- [x] I am using a stable Neovim release version, or if I am using a dev version of Neovim I have confirmed that my issue is reproducible on a stable version.

### Operating System

Fedora 37

### Minimal Config

```Lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.g.loaded_remote_plugins = ""
vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = { null_ls.builtins.diagnostics.rpmspec },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            "neovim/nvim-lspconfig",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to Reproduce

If I open an RPM spec file and try to use `gq` to format some text longer than 79 chars, it doesn't work!

### Reproducibility Check

- [X] I confirm that my minimal config is based on the `minimal_init.lua` template and that my issue is reproducible by running `nvim --clean -u minimal_init.lua` and following the steps above.

### Expected Behavior

There are two things which fix it. 

1. I can use `:LspStop` and then do `gq` which works
2. I can got to https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/rpc.lua#L33-L34 and set both values to false.

So it looks like null-ls always advertises that it can do formatting even if a builtin provider isn't able to fulfill these requests. I think setting those should be based on the `method` of a builtin.

### Actual Behavior

See above.

### Debug Log

```
[TRACE Sat Mar  4 15:26:24 2023] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:97: starting null-ls client
[TRACE Sat Mar  4 15:26:24 2023] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:102: received LSP request for method initialize
[DEBUG Sat Mar  4 15:26:24 2023] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:152: unable to notify client for method textDocument/didOpen (client not active): {
  textDocument = {
    uri = "file:///home/asn/null-ls/rustup.spec"
  }
}
[TRACE Sat Mar  4 15:26:24 2023] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method initialized
[TRACE Sat Mar  4 15:26:24 2023] .../site/pack/packer/start/null-ls.nvim/lua/null-ls/rpc.lua:127: received LSP notification for method textDocument/didOpen
[TRACE Sat Mar  4 15:26:24 2023] ...ack/packer/start/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Sat Mar  4 15:26:24 2023] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:320: spawning command "rpmspec" at /home/asn/null-ls with args { "-P", "/home/asn/null-ls/.null-ls_814785_rustup.spec" }
[TRACE Sat Mar  4 15:26:24 2023] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:204: error output: error: /home/asn/null-ls/.null-ls_814785_rustup.spec: line 30: %endif with no %if

[TRACE Sat Mar  4 15:26:24 2023] ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: output: nil
[TRACE Sat Mar  4 15:26:24 2023] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:181: received diagnostics from source 1
[TRACE Sat Mar  4 15:26:24 2023] ...ck/packer/start/null-ls.nvim/lua/null-ls/diagnostics.lua:182: { {
    bufnr = 3,
    col = 0,
    end_col = 0,
    end_lnum = 30,
    filename = "/home/asn/null-ls/.null-ls_814785_rustup.spec",
    lnum = 29,
    message = "%endif with no %if",
    row = "30",
    severity = 1,
    source = "rpmspec"
  } }
```

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by cryptomilk** [comment] 2023-03-04 14:44
If an LSP is active and advertises documentFormattingProvider/documentRangeFormattingProvider as true, then `formatexpr` gets set to `formatexpr=v:lua.vim.lsp.formatexpr`. If you set documentFormattingProvider/documentRangeFormattingProvider to false it wont be set.

**Comment by jose-elias-alvarez** [comment] 2023-03-04 19:44
This is a duplicate of #1131, I think. [This comment](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1131#issuecomment-1256227550) describes the issue and why solving it is not straightforward. Several workarounds are also documented there.

**Closed by jose-elias-alvarez** 2023-03-04 19:44 UTC
Labels: bug
