### ISSUE TITLE
shfmt args no longer work

### ISSUE THREAD

**Issue by joshuarubin** [jose-elias-alvarez/null-ls.nvim#907] opened 2022-06-10 22:29 UTC
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/7540baa0d5ca766a1958bb44c235dce990d98ce1/lua/null-ls/builtins/formatting/shfmt.lua#L16

Looks like newer versions of shfmt no longer use this form. I had to update my config to look like:
```lua
		null_ls.builtins.formatting.shfmt.with({
			args = {},
		}),
```

**Comment by jose-elias-alvarez** [comment] 2022-06-11 02:55
Which version are you using? I am on 3.5.1 and don't see any issues. I also don't see anything in [the changelog](https://github.com/mvdan/sh/releases) that would account for this.

**Comment by joshuarubin** [comment] 2022-06-16 20:33
```
λ shfmt -h
usage: shfmt [flags] [path ...]

shfmt formats shell programs. If the only argument is a dash ('-') or no
arguments are given, standard input will be used. If a given path is a
directory, all shell scripts found under that directory will be used.

  --version  show version and exit

  -l,  --list      list files whose formatting differs from shfmt's
  -w,  --write     write result to file instead of stdout
  -d,  --diff      error with a diff when the formatting differs
  -s,  --simplify  simplify the code
  -mn, --minify    minify the code to reduce its size (implies -s)

Parser options:

  -ln, --language-dialect str  bash/posix/mksh/bats, default "auto"
  -p,  --posix                 shorthand for -ln=posix
  --filename str               provide a name for the standard input file

Printer options:

  -i,  --indent uint       0 for tabs (default), >0 for number of spaces
  -bn, --binary-next-line  binary ops like && and | may start a line
  -ci, --case-indent       switch cases will be indented
  -sr, --space-redirects   redirect operators will be followed by a space
  -kp, --keep-padding      keep column alignment paddings
  -fn, --func-next-line    function opening braces are placed on a separate line

Utilities:

  -f, --find   recursively find all shell files and print the paths
  --tojson     print syntax tree to stdout as a typed JSON

For more information, see 'man shfmt' and https://github.com/mvdan/sh.
λ shfmt --version
3.5.0
```

**Comment by jose-elias-alvarez** [comment] 2022-06-16 21:08
Not sure what to say - I'd suggest updating to 3.5.1, but I can't imagine it would make much of a difference. You can see in the commit history for #290 that another user was having similar issues that were caused by a version incompatibility, though.

What happens when you run `cat $FILE | shfmt -filename $FILE` from the command line (where `$FILE` is the path to a file that `shfmt` can handle)?

**Comment by andrewferrier** [comment] 2022-07-15 14:51
I think the confusion here might come from the fact that `-filename` provides the filename (in a literal sense) - but not the content to work on. That still has to be piped into `shfmt`. So a full standalone invocation would look like:

`shfmt -filename script.sh < script.sh`

I don't know *why* `shfmt` behaves like this, but it does. https://github.com/mvdan/sh/releases/tag/v3.2.0 also hints at this behaviour.

I wonder if that's what's confusing you @joshuarubin ?

Confirmed I have done the above on 3.5.1 and it worked fine, and `null-ls` also works.

**Comment by joshuarubin** [comment] 2022-07-26 16:05
I just tested again and it continues to be broken unless I have `null_ls.builtins.formatting.shfmt.with({ args = {} })`.

**Comment by vladdoster** [comment] 2022-08-18 08:35
Isn't the issue that the flag should be `--filename`?

**Comment by jose-elias-alvarez** [comment] 2022-09-06 20:01
> Isn't the issue that the flag should be `--filename` whereas it is currently `-filename`?

I'm not sure about this. `shfmt --help` does list [`--filename`](https://github.com/mvdan/sh/blob/5e16174ffae00ad0e3f1fe878c9fb3ddbca6c7ec/cmd/shfmt/main.go#L159) (with two dashes), but [the changelog](https://github.com/mvdan/sh/blob/169e304e539728a7a8fbb4ff5828d5c211790e85/CHANGELOG.md#320---2020-10-29) uses `-filename`, and it's also mentioned in [this issue](https://github.com/mvdan/sh/issues/889).

To my knowledge, this is working as intended, and I don't have the information I need to debug this (at a minimum I need to know what happens when running this from the command line) so I'm going to close the issue.

**Closed by jose-elias-alvarez** 2022-09-06 20:01 UTC
