### ISSUE TITLE
Error detected while processing BufNewFile Autocommands for "*":

### ISSUE THREAD

**Issue by SingularisArt** [jose-elias-alvarez/null-ls.nvim#1104] opened 2022-09-13 22:03 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.8.0-dev-973-g253f0ffd8d

### Operating System

Arch Linux

### Minimal config

```lua
------------
-- Packer --
------------

local fn = vim.fn

local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
  PACKER_BOOTSTRAP = fn.system({
    "git",
    "clone",
    "--depth",
    "1",
    "https://github.com/wbthomason/packer.nvim",
    install_path,
  })
  print("Installing packer close and reopen Neovim...")
  vim.cmd([[packadd packer.nvim]])
end

local status_ok, packer = pcall(require, "packer")
if not status_ok then
  return
end

require("packer").startup(function(use)
  use({ "neovim/nvim-lspconfig" })
  use({ "tamago324/nlsp-settings.nvim" })
  use({ "jose-elias-alvarez/null-ls.nvim" })

  if PACKER_BOOTSTRAP then
    packer.sync()
  end
end)

if #vim.api.nvim_list_uis() == 0 then
  return
end

-------------
-- Null LS --
-------------

local null_ls = require("null-ls")

-- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
local formatting = null_ls.builtins.formatting
-- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
local diagnostics = null_ls.builtins.diagnostics

-- https://github.com/prettier-solidity/prettier-plugin-solidity
-- npm install --save-dev prettier prettier-plugin-solidity
null_ls.setup({
  debug = true,
  sources = {
    formatting.prettier.with({
      extra_filetypes = { "toml", "solidity" },
      extra_args = { "--no-semi", "--single-quote", "--jsx-single-quote" },
    }),
    formatting.standardrb.with({
      extra_filetypes = { "--fix", "--format", "quiet", "--stderr", "--stdin", "$FILENAME" },
    }),
    formatting.black.with({
      extra_args = { "--fast" },
    }),
    formatting.clang_format,
    formatting.rustfmt,
    formatting.sql_formatter,
    formatting.stylua,
    formatting.google_java_format,
    formatting.shellharden,

    diagnostics.flake8,
    diagnostics.shellcheck,
    diagnostics.cppcheck,
  },
})
```

### Steps to reproduce

1. Copy the minimal config I provided into the `init.lua`.
2. Run `nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`.
3. Open `nvim` again.
4. Open a `.py` file and you can see the error I'm getting.

### Expected behavior

I expect that the formatters and diagnostics would work.

### Actual behavior

Any time I open a filetype that I have a formatter or diagnostic for, it gives the error above. For example, if I have black and or flake8 enabled, I open a python file and get the error—something with Lua, java, rust, ruby, bash, etc.

### Debug log

[TRACE Tue 13 Sep 2022 02:44:29 PM PDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Tue 13 Sep 2022 02:44:30 PM PDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client
[TRACE Tue 13 Sep 2022 02:44:30 PM PDT] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:110: starting null-ls client

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment] 2022-09-13 22:31
What is the error message you are seeing? Please follow the instructions in the issue template - your config is not standalone, so I cannot reproduce this. Also, please update to the latest Neovim master.

**Comment by SingularisArt** [comment] 2022-09-13 22:38
I'm using the latest version of null-ls and neovim. Here's a screenshot of what I'm seeing:

![Screenshot_2022-09-13_15-37-16](https://user-images.githubusercontent.com/57925294/190021431-5d1827bd-ebb7-4e01-af14-9c89dea7d619.png)

wdym my config isn't standalone? Did I miss something, or am I adding too much configuration?

**Comment by jose-elias-alvarez** [comment] 2022-09-13 22:44
The error comes from running a version of Neovim that does not have neovim/neovim@126fe7fbc9c88c412c8067d9d146d998baf6dd47 merged, so updating will solve it.

**Closed by jose-elias-alvarez** 2022-09-13 22:44 UTC
Labels: bug
