### ISSUE TITLE
Eslint_d error -  File ignored by default

### ISSUE THREAD

**Issue by lucasmoura-boticario** [jose-elias-alvarez/null-ls.nvim#691] opened 2022-02-17 20:01 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

v0.6.1

### Operating System

MacOSX  12.0.1

### Minimal config

```
local null_ls = require('null-ls')

null_ls.setup({
    debug = true,
    sources = {
      null_ls.builtins.diagnostics.eslint_d.with({
      extra_args = {"--stdin-filename", ".eslintrc.js"}
      }), -- eslint or eslint_d
      null_ls.builtins.formatting.eslint -- prettier, eslint, eslint_d, or prettierd
    },
})

null_ls.setup()

```

### Steps to reproduce

Diagnostic log

```
[TRACE Qui 17 Fev 16:58:34 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method shutdown
[TRACE Qui 17 Fev 16:58:34 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method exit
[TRACE Qui 17 Fev 16:58:41 2022] ...l/share/nvim/plugged/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
[TRACE Qui 17 Fev 16:58:41 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[TRACE Qui 17 Fev 16:58:41 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Qui 17 Fev 16:58:41 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Qui 17 Fev 16:58:41 2022] ...are/nvim/plugged/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Qui 17 Fev 16:58:41 2022] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:18: attempting to find local executable node_modules/.bin/eslint_d
[DEBUG Qui 17 Fev 16:58:41 2022] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:40: Unable to resolve command [node_modules/.bin/eslint_d], skipping further lookups
[DEBUG Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:281: Using dynamic command for [eslint_d], got: eslint_d
[DEBUG Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:335: spawning command [eslint_d] at /Users/lucaslo/Dev/clickgb-frontend with args { "-f", "json", "--stdin", "--stdin-filename", "/Users/lucaslo/Dev/clickgb-frontend/src/modules/newHome/components/recentPageWidget/recentPageWidget.component.tsx", "--stdin-filename", ".eslintrc.js" }
[TRACE Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
[TRACE Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:225: output: [{"filePath":"/Users/lucaslo/Dev/clickgb-frontend/.eslintrc.js","messages":[{"fatal":false,"severity":1,"message":"File ignored by default.  Use a negated ignore pattern (like \"--ignore-pattern '!<relative/path/to/filename>'\") to override."}],"errorCount":0,"warningCount":1,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"jsx-a11y/accessible-emoji","replacedBy":[]},{"ruleId":"lines-around-directive","replacedBy":["padding-line-between-statements"]},{"ruleId":"no-spaced-func","replacedBy":["func-call-spacing"]},{"ruleId":"global-require","replacedBy":[]},{"ruleId":"no-buffer-constructor","replacedBy":[]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
[TRACE Qui 17 Fev 16:58:41 2022] ...re/nvim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:162: received diagnostics from source 1
[TRACE Qui 17 Fev 16:58:41 2022] ...re/nvim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:163: { {
    col = 0,
    end_col = 0,
    end_lnum = 1,
    lnum = 0,
    message = "File ignored by default.  Use a negated ignore pattern (like \"--ignore-pattern '!<relative/path/to/filename>'\") to override.",
    severity = 2,
    source = "eslint_d"
  } }

```

Output terminal eslint_d:

```
➜  clickgb-frontend git:(feat/new-home) ✗ eslint_d src/modules/newHome/components/recentPageWidget/recentPageWidget.component.tsx

/Users/lucaslo/Dev/clickgb-frontend/src/modules/newHome/components/recentPageWidget/recentPageWidget.component.tsx
   1:22  error    Strings must use singlequote   quotes
   7:3   warning  Unexpected console statement   no-console
  17:34  warning  'i' is defined but never used  @typescript-eslint/no-unused-vars

✖ 3 problems (1 error, 2 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

### Expected behavior

Show diagnostic error

```
  1:22  error    Strings must use singlequote   quotes
   7:3   warning  Unexpected console statement   no-console
  17:34  warning  'i' is defined but never used  @typescript-eslint/no-unused-vars
```

### Actual behavior

 File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override.

### Debug log

```
[TRACE Qui 17 Fev 16:58:34 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method shutdown
[TRACE Qui 17 Fev 16:58:34 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method exit
[TRACE Qui 17 Fev 16:58:41 2022] ...l/share/nvim/plugged/null-ls.nvim/lua/null-ls/client.lua:92: starting null-ls client
[TRACE Qui 17 Fev 16:58:41 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:118: received LSP request for method initialize
[TRACE Qui 17 Fev 16:58:41 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method initialized
[TRACE Qui 17 Fev 16:58:41 2022] ...ocal/share/nvim/plugged/null-ls.nvim/lua/null-ls/rpc.lua:143: received LSP notification for method textDocument/didOpen
[TRACE Qui 17 Fev 16:58:41 2022] ...are/nvim/plugged/null-ls.nvim/lua/null-ls/generators.lua:21: running generators for method NULL_LS_DIAGNOSTICS_ON_OPEN
[DEBUG Qui 17 Fev 16:58:41 2022] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:18: attempting to find local executable node_modules/.bin/eslint_d
[DEBUG Qui 17 Fev 16:58:41 2022] ...ed/null-ls.nvim/lua/null-ls/helpers/command_resolver.lua:40: Unable to resolve command [node_modules/.bin/eslint_d], skipping further lookups
[DEBUG Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:281: Using dynamic command for [eslint_d], got: eslint_d
[DEBUG Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:335: spawning command [eslint_d] at /Users/lucaslo/Dev/clickgb-frontend with args { "-f", "json", "--stdin", "--stdin-filename", "/Users/lucaslo/Dev/clickgb-frontend/src/modules/newHome/components/recentPageWidget/recentPageWidget.component.tsx", "--stdin-filename", ".eslintrc.js" }
[TRACE Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:224: error output: nil
[TRACE Qui 17 Fev 16:58:41 2022] ...d/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:225: output: [{"filePath":"/Users/lucaslo/Dev/clickgb-frontend/.eslintrc.js","messages":[{"fatal":false,"severity":1,"message":"File ignored by default.  Use a negated ignore pattern (like \"--ignore-pattern '!<relative/path/to/filename>'\") to override."}],"errorCount":0,"warningCount":1,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[{"ruleId":"jsx-a11y/accessible-emoji","replacedBy":[]},{"ruleId":"lines-around-directive","replacedBy":["padding-line-between-statements"]},{"ruleId":"no-spaced-func","replacedBy":["func-call-spacing"]},{"ruleId":"global-require","replacedBy":[]},{"ruleId":"no-buffer-constructor","replacedBy":[]},{"ruleId":"no-new-require","replacedBy":[]},{"ruleId":"no-path-concat","replacedBy":[]}]}]
[TRACE Qui 17 Fev 16:58:41 2022] ...re/nvim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:162: received diagnostics from source 1
[TRACE Qui 17 Fev 16:58:41 2022] ...re/nvim/plugged/null-ls.nvim/lua/null-ls/diagnostics.lua:163: { {
    col = 0,
    end_col = 0,
    end_lnum = 1,
    lnum = 0,
    message = "File ignored by default.  Use a negated ignore pattern (like \"--ignore-pattern '!<relative/path/to/filename>'\") to override.",
    severity = 2,
    source = "eslint_d"
  } }

```

### Help

No

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment] 2022-02-17 20:41
Are you sure this line is correct?

```lua
extra_args = {"--stdin-filename", ".eslintrc.js"}
```

I can't replicate your specific error but this could definitely cause problems.

**Comment by lucasmoura-boticario** [comment] 2022-02-17 20:43
Wouldn't this be the correct way to say what my file is?

**Comment by lucasmoura-boticario** [comment] 2022-02-17 20:43
Sorry, removing it looks like he managed to understand the eslint

**Comment by lucasmoura-boticario** [comment] 2022-02-17 20:44
![image](https://user-images.githubusercontent.com/80352333/154567580-536c1f0b-5079-430d-a7d0-a4c074a10a66.png)

**Comment by lucasmoura-boticario** [comment] 2022-02-17 20:46
only the command :lua vim.lsp.buf.formatting() is not working now

**Comment by jose-elias-alvarez** [comment] 2022-02-18 01:56
`eslint_d` formatting with your config is working fine on my end. ESLint is complex, and there's too many variables involved for me to determine what the issue is with limited information. The only way I can investigate it is if you replicate the issue using a full minimal config, post logs, and also provide a file / project I can use to reproduce:

> Download the minimal config using `curl -fLO https://raw.githubusercontent.com/jose-elias-alvarez/null-ls.nvim/main/scripts/minimal_init.lua`. Edit it to include the configuration necessary to reproduce your bug and paste it here.

**Comment by strange** [comment] 2022-02-26 23:07
Same problem here. The errors are reported but aren't fixed with `:lua vim.lsp.buf.formatting_sync()`. Prettier and deno work fine.

**Comment by jose-elias-alvarez** [comment] 2022-02-27 00:35
@strange Is this same the issue or a general formatting issue? Either way I can't act on this without a minimal reproduction.

**Comment by strange** [comment] 2022-02-27 15:27
> only the command :lua vim.lsp.buf.formatting() is not working now

That part. That does nothing when I have enabled `eslint` or `eslint_d` formatters. Works with `!eslint --fix %` or other formatters.

**Comment by idevat** [comment] 2022-04-05 09:07
@strange I've had similar issue: combination `prettier_d_slim` and `eslint_d` didn't work. `prettier_d_slim` alone worked fine but `eslint_d` alone didn't work. Also `!eslint --fix %` worked. Killing eslint_d fixed it after some time of various desperate attempts.

**Comment by jose-elias-alvarez** [comment] 2022-05-15 17:50
Closing this since I don't have the information necessary to investigate further, but feel free to open another issue with full reproduction steps if you're still having this problem.

**Closed by jose-elias-alvarez** 2022-05-15 17:50 UTC
Labels: bug
