### ISSUE TITLE
[Bug]: `Error detected while processing CursorHold Autocommands for "*":`

### ISSUE THREAD

**Issue by sandersantema** [jose-elias-alvarez/null-ls.nvim#14] opened 2021-06-19 13:37 UTC
This is the error which popped-up using null-ls 0bb8b386b272c44f5214f135aeec978705fbce99 and `NVIM v0.5.0-dev+1425-g7da86f55a`

```
Error detected while processing CursorHold Autocommands for "*":
E5108: Error executing lua vim/shared.lua:314: src: expected table, got number
stack traceback:
        vim/shared.lua:314: in function 'list_extend'
        .../pack/packer/start/null-ls.nvim/lua/null-ls/handlers.lua:46: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1276: in function 'buf_request'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:192: in function 'code_action'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:276: in function 'code_action_prompt'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

As you can see it happens for a buffer where null-ls isn't an active client:
![image](https://user-images.githubusercontent.com/21057514/122644033-4b217600-d113-11eb-84cd-81ec7ce54238.png)

**Steps to reproduce:**
1. Restrict null-ls to some filetypes
2. Open a buffer of one of the aforementioned filetypes such that null-ls is an active client
3. Open another buffer for which you have other registered lsp's but not null-ls 
4. Hover

Edit: nice to see github finally implemented markdown for issue titles :)

**Comment by jose-elias-alvarez** [comment] 2021-06-20 04:49
Hmm, I don't use lspsaga but am having trouble replicating this with a default setup. Have you modified your lspsaga configuration at all? Your screenshot is strange, too, because it seems like the null-ls client has shut down completely (given the reproduction steps, it should be listed under `Active clients` but not `client(s) attached to this buffer`). 

Based on your stack trace, I *think* aa8d31f038e568870922b07044d6eadd8722ea4f should take care of the problem, but if not, I might need some more information about your setup to replicate and debug the error, so let me know.

**Comment by jose-elias-alvarez** [comment] 2021-07-17 09:56
Closing this for now! Feel free to open another issue if I wasn't able to fix it.

**Closed by jose-elias-alvarez** 2021-07-17 09:56 UTC

**Comment by sandersantema** [comment] 2021-07-17 12:16
Heya, sorry forgot about this issue but that's for a good reason because it has resolved itself :) (and because I'm forgetful but that's besides the point). So all is good!
