### ISSUE TITLE
eslint spawns too many processes

### ISSUE THREAD

**Issue by cloudlena** [jose-elias-alvarez/null-ls.nvim#596] opened 2022-01-18 10:55 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.1

### Operating System

Arch Linux

### Minimal config

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local null_ls_config = function()
    local null_ls = require("null-ls")
    -- add only what you need to reproduce your issue
    null_ls.setup({
        sources = { null_ls.builtins.diagnostics.eslint },
        debug = true,
    })
end

local function load_plugins()
    -- only add other plugins if they are necessary to reproduce the issue
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            {
                "jose-elias-alvarez/null-ls.nvim",
                requires = { "nvim-lua/plenary.nvim" },
                config = null_ls_config,
            },
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
else
    load_plugins()
    require("packer").sync()
end
```

### Steps to reproduce

Open TypeScript or JavaScript project with `null_ls.builtins.diagnostics.eslint` as source and make many edits in a short amount of time.

### Expected behavior

I expect null-ls to terminate unused `eslint` processes. I'm guessing that null-ls just spawns more `eslint` processes for every edit I make without cancelling the existing ones which, at that point, are not used anymore.

### Actual behavior

null-ls spawns many different `eslint` processes when I make many changes in a small time frame.

![screenshot-2022-01-18-11-37-28](https://user-images.githubusercontent.com/6780471/149923706-643eec18-d003-4749-b3c4-46cb3cc8acc1.png)

### Debug log

No log lines

### Help

Yes, but I don't know how to start. I would need guidance

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by jose-elias-alvarez** [comment] 2022-01-18 15:31
Your analysis is right. Each normal mode change will trigger a `textDocument/didChange` notification, and each notification will cause null-ls to spawn a fresh copy of `eslint` (this is modulated by the `debounce_text_changes` flag, which [null-ls exposes as `debounce`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/CONFIG.md#debounce-number)). Fundamentally this is only an issue for slow linters, and vanilla `eslint` is one of the slowest, especially when your config contains a lot of rules.

The ideal behavior in the case you describe is to cancel running generators so that we only keep the newest. As I mentioned in #307, there is an open Plenary PR to add cancellation support, but it seems to have stalled (and I'm not nearly experienced enough with coroutines to help). That would be the best solution overall, but it's out of my control. 

Other than that, we could track previous spawns of the same process and cancel those if they are still running (I believe this is what efm-langserver does). This is a very, very rough sketch of what that might look like (we would want to index by URI or something similar that's unique to each spawned instance):

```diff
diff --git a/lua/null-ls/loop.lua b/lua/null-ls/loop.lua
index 17b496f..c1fb4f7 100644
--- a/lua/null-ls/loop.lua
+++ b/lua/null-ls/loop.lua
@@ -4,6 +4,8 @@ local u = require("null-ls.utils")
 local uv = vim.loop
 local wrap = vim.schedule_wrap

+local previous_spawn = {}
+
 local close_handle = function(handle)
     if handle and not handle:is_closing() then
         handle:close()
@@ -45,8 +47,12 @@ local TIMEOUT_EXIT_CODE = 7451
 local M = {}

 M.spawn = function(cmd, args, opts)
-    local handler, input, check_exit_code, timeout, on_stdout_end, env =
-        opts.handler, opts.input, opts.check_exit_code, opts.timeout, opts.on_stdout_end, opts.env
+    local handler, input, check_exit_code, timeout, on_stdout_end, env, id =
+        opts.handler, opts.input, opts.check_exit_code, opts.timeout, opts.on_stdout_end, opts.env, opts.id
+
+    if id and previous_spawn[id] then
+        previous_spawn[id]()
+    end

     local output, error_output = "", ""
     local handle_stdout = function(err, chunk)
@@ -155,6 +161,17 @@ M.spawn = function(cmd, args, opts)
             close_handle(stdin)
         end)
     end
+
+    if id then
+        previous_spawn[id] = function()
+            if handle then
+                print("killing", id)
+                uv.process_kill(handle, "SIGINT")
+                on_close(0)
+            end
+            previous_spawn[id] = nil
+        end
+    end
 end

 M.timer = function(timeout, interval, should_start, callback)
```

Something like this would also make the workaround I introduced in #320 unnecessary and generally speed up performance in the worst cases. Let me know if the diff above actually solves your issue and if you're up for a PR (I won't have time to work on it myself for a bit).

**Comment by jose-elias-alvarez** [comment] 2022-01-18 15:35
Also, to make sure: With the current behavior, are the processes correctly cleaned up after they finish? I haven't been able to get so many processes to persist on my end (though I don't work on any massive projects and have a fairly fast CPU).

**Comment by cloudlena** [comment] 2022-01-19 17:31
Thanks, @jose-elias-alvarez! I just tried your diff locally, and unfortunately it didn't solve the problem. I saw no change in the described behavior.

**Comment by jose-elias-alvarez** [comment] 2022-01-19 20:09
I see, in that case I wonder if there's something else going on. I'm able to get null-ls to spawn a bunch of ESLint processes and kill them with the proposed patch, but I can't get them to persist as in your screenshot. 

Without a reliable way to reproduce this, I don't know if there's much more I can do to investigate. [Enabling debug logging](https://github.com/jose-elias-alvarez/null-ls.nvim#how-do-i-enable-debug-mode-and-get-debug-output) and adding log output might help.

**Comment by shendypratamaa** [comment] 2022-01-28 15:29
> ### FAQ
> * [x]  I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.
> 
> ### Issues
> * [x]  I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.
> 
> ### Neovim Version
> NVIM v0.6.1
> 
> ### Operating System
> Arch Linux
> 
> ### Minimal config
> ```lua
> -- this template is borrowed from nvim-lspconfig
> local on_windows = vim.loop.os_uname().version:match("Windows")
> 
> local function join_paths(...)
>     local path_sep = on_windows and "\\" or "/"
>     local result = table.concat({ ... }, path_sep)
>     return result
> end
> 
> vim.cmd([[set runtimepath=$VIMRUNTIME]])
> 
> local temp_dir
> if on_windows then
>     temp_dir = vim.loop.os_getenv("TEMP")
> else
>     temp_dir = "/tmp"
> end
> 
> vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))
> 
> local package_root = join_paths(temp_dir, "nvim", "site", "pack")
> local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
> local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")
> 
> local null_ls_config = function()
>     local null_ls = require("null-ls")
>     -- add only what you need to reproduce your issue
>     null_ls.setup({
>         sources = { null_ls.builtins.diagnostics.eslint },
>         debug = true,
>     })
> end
> 
> local function load_plugins()
>     -- only add other plugins if they are necessary to reproduce the issue
>     require("packer").startup({
>         {
>             "wbthomason/packer.nvim",
>             {
>                 "jose-elias-alvarez/null-ls.nvim",
>                 requires = { "nvim-lua/plenary.nvim" },
>                 config = null_ls_config,
>             },
>         },
>         config = {
>             package_root = package_root,
>             compile_path = compile_path,
>         },
>     })
> end
> 
> if vim.fn.isdirectory(install_path) == 0 then
>     vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
>     load_plugins()
>     require("packer").sync()
> else
>     load_plugins()
>     require("packer").sync()
> end
> ```
> 
> ### Steps to reproduce
> Open TypeScript or JavaScript project with `null_ls.builtins.diagnostics.eslint` as source and make many edits in a short amount of time.
> 
> ### Expected behavior
> I expect null-ls to terminate unused `eslint` processes. I'm guessing that null-ls just spawns more `eslint` processes for every edit I make without cancelling the existing ones which, at that point, are not used anymore.
> 
> ### Actual behavior
> null-ls spawns many different `eslint` processes when I make many changes in a small time frame.
> 
> ![screenshot-2022-01-18-11-37-28](https://user-images.githubusercontent.com/6780471/149923706-643eec18-d003-4749-b3c4-46cb3cc8acc1.png)
> 
> ### Debug log
> No log lines
> 
> ### Help
> Yes, but I don't know how to start. I would need guidance
> 
> ### Implementation help
> _No response_
> 
> ### Requirements
> * [x]  I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

i have same issue if using `eslint`,  and i try to change using `eslint_d` and work as expected not high cpu load detected, but i don't know why, my configuration null-ls is default base on guidance

**Comment by jose-elias-alvarez** [comment] 2022-01-28 16:49
@shendypratamaa Using `eslint_d` essentially avoids the issue, since it runs so fast that spawning multiple processes isn't an issue. Vanilla `eslint` is painfully slow, so I always recommend using `eslint_d` or the [ESLint language server](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#eslint) if possible.

**Comment by cloudlena** [comment] 2022-01-29 13:40
I also switched to the ESLint language server by now :)
Works perfectly.

**Comment by FelipeLema** [comment] 2022-04-27 20:53
I'm having the same problem with Go files  using `revive` and `golangci-lint`. Several processes (about 20 for each ) spawned within a couple of seconds.

**Comment by gegoune** [comment] 2022-04-27 21:02
Those who switched to eslint LSP - do you still use code actions from eslint provided by null-ls?

**Comment by jose-elias-alvarez** [comment] 2022-04-27 21:26
> Those who switched to eslint LSP - do you still use code actions from eslint provided by null-ls?

No need in my experience, the server has great support for code actions (it even supports a few additional ones like documentation links).

**Comment by FelipeLema** [comment] 2022-04-28 22:00
it seems that this problem is happening to me because any-of-or-the-sum-of the following
- using tabs
- using `git worktree`s (some files opened with almost-the-same-name ... along with a couple lsp servers running)

**Comment by jose-elias-alvarez** [comment] 2022-04-28 22:42
> it seems that this problem is happening to me because any-of-or-the-sum-of the following
> 
>     * using tabs
> 
>     * using `git worktree`s (some files opened with almost-the-same-name ... along with a couple lsp servers running)

I can't investigate this without a self-contained (in the case of the OP, I wasn't able to reproduce it at all, so it may have been due to a specific project configuration).

**Comment by FelipeLema** [comment] 2022-04-29 01:53
I can help debugging this ... where should I look? do I need anything else besides `require'null-ls'.setup({ … debug = true, … })` ?

**Comment by jose-elias-alvarez** [comment] 2022-04-29 02:08
Yes, you can try debug logging to see if anything pops up there. From my prior attempt to investigate this, it's a pretty elusive issue, so you might have to dig into the source code and do some logging there to find out why processes aren't getting shut down as they should. Let's also move the discussion to a new issue if you're able to find anything.

**Comment by jose-elias-alvarez** [comment] 2022-05-15 19:20
I don't think we're going to get to the root of the original issue, especially since ESLint is so complex and depends so heavily on project-local config. The ESLint language server is mature enough now to completely replace our implementation here, so I'm going to close this specific issue. Anyone experiencing similar problems with another source should open a new issue with reproduction steps, including a project I can use to replicate on my end.

**Closed by jose-elias-alvarez** 2022-05-15 19:20 UTC
Labels: bug

**Comment by kmoschcau** [comment] 2022-10-17 13:48
Hi, I think I have a way to repro this. As mentioned in other issues I have implemented integrations for checkstyle and pmd in java. Both are not the fastest. When I run formatting on a larger java file with google-java-format, the log is spammed with "buffer changed; ignoring received diagnostics", null-ls spawns a ton of checkstyle and pmd instances, choking my machine of resources after a while. It almost seems like null-ls doesn't treat the formatting as a single change but as a ton of different changes.

Do you want to continue this here or should I open a new issue?

**Comment by jose-elias-alvarez** [comment] 2022-10-17 15:47
@kmoschcau Please put together a separate issue with a full minimal reproduction. To give you some context, this is the logic null-ls uses to determine when to run diagnostics sources:

1. When the buffer is first opened, a `didOpen` notification runs all diagnostics sources.
2. If the user makes a change in insert mode and the user has not set `update_in_insert = true` in their null-ls config, the notification is stored and flushed when the user next exits insert mode. (This is different from Neovim's `update_in_insert` setting, which simply hides diagnostics but does not affect notifications.)
3. If the user makes a change and is not in insert mode, the `didChange` notification is immediately sent to the client, which runs all applicable diagnostics sources.

However, null-ls passes the value of the `debounce` config setting to Neovim, which is responsible for [debouncing these notifications](https://github.com/neovim/neovim/blob/5046b4b4adb154bbdb50a5e96e29f777b5f807ac/runtime/lua/vim/lsp.lua#L360). It's possible to disable this behavior, but that would be an issue with the user's configuration.

I can verify that with the default value of `debounce = 250`, commenting out or otherwise changing multiple lines at a time only triggers a single notification. This may spawn multiple processes if multiple sources can run on a given buffer, but it should not spawn multiple copies of the same buffer (and either way those processes should not stay alive). It *is* possible to trigger a large number of notifications by, say, spamming `x`, but that's solvable by increasing the `debounce` value.

I investigated this issue in the past and was not able to replicate it or identify what could be causing it, so in the absence of a full minimal reproduction - meaning a standalone Neovim config as well as a file / project I can use to replicate it on my end - there's not much I can do.
