### ISSUE TITLE
Diagnostics returning out-of-bounds characters

### ISSUE THREAD

**Issue by pohzipohzi** [jose-elias-alvarez/null-ls.nvim#164] opened 2021-09-07 20:38 UTC
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

0.6.0-dev+3f526feeb

### Steps to reproduce

See https://github.com/neovim/neovim/issues/15591

From neovim client's perspective, this happens due to -1 being returned as an end character (see [comment](https://github.com/neovim/neovim/issues/15591#issuecomment-914460303)). When I looked through the code, it appears that there's no special handling when converting ranges if end_col does not exist (also see [comment](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/diagnostics.lua#L14)).

We can perhaps handle it by incrementing the line number and setting column to 0. From the LSP [doc](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#range):

> If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.

The following diff seems to fix the issue:

```
diff --git a/lua/null-ls/utils.lua b/lua/null-ls/utils.lua
index 734fd6d..29e0244 100644
--- a/lua/null-ls/utils.lua
+++ b/lua/null-ls/utils.lua
@@ -76,8 +76,8 @@ M.range = {
                 character = range.col - 1,
             },
             ["end"] = {
-                line = range.end_row - 1,
-                character = range.end_col - 1,
+                line = range.end_col > 0 and range.end_row - 1 or range.end_row,
+                character = range.end_col > 0 and range.end_col - 1 or 0,
             },
         }
         return lsp_range
```

**Comment by jose-elias-alvarez** [comment] 2021-09-08 02:46
Thanks for looking into this! Handling missing ranges takes place in the [diagnostics handler](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/235f234e7068b5921e3fddcc12768aa691439369/lua/null-ls/diagnostics.lua#L9), since my logic was that the method you found should only be responsible for conversion.

Just so I understand: Is it correct to say that `-1` working was just a quirk of the previous implementation? Either way, LSP compliance is of course a good idea, and your change makes sense, so I've implemented it.

**Comment by jose-elias-alvarez** [comment] 2021-09-08 03:15
I've tested this out with the specific file and config that was causing an issue in neovim/neovim#15591, but it seems that shifting ranges as described in the LSP spec doesn't work if the next line doesn't exist. Given the following content:

```python
#comment
import test

if __name__ == "__main__":
    main()
```

The diagnostics from the last line are shown in the sign column and by `vim.lsp.diagnostic.show_line_diagnostics()` but not when calling `vim.lsp.diagnostic.goto_prev()` or `vim.lsp.diagnostic.goto_next()`. (I use a theme that supports highlighting LSP diagnostics, and I can see that the line isn't highlighted correctly, either.) Inserting a blank line after the last line makes everything work correctly. 

Since (if I understand correctly and if I didn't mess anything up) the behavior is now in line with the spec, I wonder if this is a Neovim issue. (I also simplified diagnostic conversion in 6ba3fcf811f32ef4d96e670437e26bb1a43b98b7, which should hopefully make it easier to see what's going on.)

**Comment by jose-elias-alvarez** [comment] 2021-09-08 10:57
Based on the discussion in the linked Neovim issue, is it safe to conclude that null-ls is now behaving correctly and fixing the display of diagnostics in the case I described needs to be handled on the Neovim side?

**Comment by mjlbach** [comment] 2021-09-08 15:42
I'm a bit confused by what is the upstream issue? The linked issue refers to us normalizing the diagnostic line ranges so they fall within valid buffer lines and skip the terminating newline that is appended in neovim/vim by default with fixeol.

**Comment by jose-elias-alvarez** [comment] 2021-09-08 16:10
I think perhaps I’m misunderstanding the cause of the issue I described, then. To rephrase my question:  Is null-ls now doing the right thing, or is there something else we can change / fix here?

**Comment by pohzipohzi** [comment] 2021-09-09 23:23
@jose-elias-alvarez I believe null-ls is doing the right thing :slightly_smiling_face: we are attempting a fix in neovim, let's see how it goes

**Comment by jose-elias-alvarez** [comment] 2021-09-16 13:57
Thanks for confirming! Going to close this for now but feel free to open another issue if our behavior here is wrong.

**Closed by jose-elias-alvarez** 2021-09-16 13:57 UTC
Labels: bug
