### ISSUE TITLE
Builtin args are not extendable

### ISSUE THREAD

**Issue by Tastyep** [jose-elias-alvarez/null-ls.nvim#105] opened 2021-08-13 07:30 UTC
Example:

``` lua
local luacheck = null_ls.builtins.diagnostics.luacheck
luacheck = luacheck.with({args = { myargs }})
```

Expected:

``` lua
luacheck.args = { myargs + null_ls defined args }
```

Actual:

``` lua
luacheck.args = { myargs }
```

That's unfortunately the behavior of `vim.tbl_deep_extend`, for a list, it will overwrite it instead of extending it.

So then I thought about doing

``` lua
local luacheck = null_ls.builtins.diagnostics.luacheck
vim.list_extend(myargs, luacheck._opts.args)
luacheck = luacheck.with({args = { myargs }})
```

But then it didn't work for [other builtins](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting.lua#L372)
Some of them have a table as args, others have a function, this would need to be streamlined.

**Comment by jose-elias-alvarez** [comment] 2021-08-13 07:42
This would be really useful. I just dealt with a similar situation and realized that wrapping `args` in a function could be a solution. I haven't tested this thoroughly, but does this diff do what you want?

```diff
diff --git a/lua/null-ls/helpers.lua b/lua/null-ls/helpers.lua
index 033faa3..6a10562 100644
--- a/lua/null-ls/helpers.lua
+++ b/lua/null-ls/helpers.lua
@@ -278,6 +278,19 @@ M.make_builtin = function(opts)

     builtin.with = function(user_opts)
         builtin.filetypes = user_opts.filetypes or builtin.filetypes
+
+        if type(user_opts.args) == "table" then
+            local original_args = builtin._opts.args
+            local extended_args = user_opts.args
+            builtin._opts.args = function(params)
+                local args = type(original_args) == "function" and original_args(params) or original_args
+                return vim.list_extend(args, extended_args)
+            end
+
+            -- clear to avoid duplicating
+            user_opts.args = nil
+        end
+
         builtin._opts = vim.tbl_deep_extend("force", builtin._opts, user_opts)

         local condition = user_opts.condition
```

**Comment by Tastyep** [comment] 2021-08-13 07:56
That would probably do it, few remarks I have about the code snippet

`if type(user_opts.args) == "table" then`
This fails silently for unsupported args type
IMO it should be
`if user_opts.args then`

I don't think `vim.list_extend` actually returns anything, it replaces in place.

Builtins with a function as base args cannot be extended

I'm wondering if doing `{user_args + builtin_args}` would be better than `{builtin_args + user_args}`
For instance what happens with [luacheck](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics.lua#L43) and the "-" parameter to indicate stdin if it's not at the end ? To be tested.

**Comment by jose-elias-alvarez** [comment] 2021-08-13 08:09
The logic behind the typecheck was to let the user override `args` with a function, since odds are they don't want to merge the arguments in that case. On that note, it's probably not a good idea to do this by default, since it's likely to break existing configs. 

Perhaps we can handle this by having an `extra_args` field, as well as an option to determine whether the extra arguments are inserted before or after the original arguments. I think it makes sense to default to after, since I imagine that's more in line with user expectations. 

> Builtins with a function as base args cannot be extended

What do you mean? I tried this out with `prettier`, which uses a function to handle range formatting, and it seems to work (unless I'm misunderstanding what you want).

**Comment by jose-elias-alvarez** [comment] 2021-08-13 08:22
Also, I saw in your linked PR that you're handling `eslint_d` as a special case. I've got a commit ready to go that adds a separate `eslint_d` diagnostics built-in, so I think you'll be able to handle it normally once it's merged.

**Comment by Tastyep** [comment] 2021-08-13 08:23
> Also, I saw in your linked PR that you're handling `eslint_d` as a special case. I've got a commit ready to go that adds a separate `eslint_d` diagnostics built-in, so I think you'll be able to handle it normally once it's merged.

Great, that will simplify some logic, thank you about that

**Comment by kylo252** [comment] 2021-08-13 08:27
I think it might be better to stick to `vim.tbl_deep_extend` if possible. You can use `vim.tbl_islist` if it helps.


```
tbl_islist({t})                                             *vim.tbl_islist()*
                Tests if a Lua table can be treated as an array.

                Empty table `{}` is assumed to be an array, unless it was
                created by |vim.empty_dict()| or returned as a dict-like |API|
                or Vimscript result, for example from |rpcrequest()| or
                |vim.fn|.

                Parameters: ~
                    {t}  Table

                Return: ~
                    `true` if array-like table, else `false` .
```

**Comment by Tastyep** [comment] 2021-08-13 08:32
> The logic behind the typecheck was to let the user override `args` with a function, since odds are they don't want to merge the arguments in that case. On that note, it's probably not a good idea to do this by default, since it's likely to break existing configs and doesn't line up with the behavior of other fields in `with`.

Like you said, it's likely to break things more than anything else.
[Example](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/diagnostics.lua#L20) if the format is lost, the output won't be parsable.

> Perhaps we can handle this by having an `extra_args` field, as well as an option to determine whether the extra arguments are inserted before or after the original arguments. I think it makes sense to default to after, since I imagine that's more in line with user expectations, but I'm open to either.

Well, I agree that for overriding it would make more sens to provide arguments after the defaults (in theory at least), however, I don't think null-ls should specify arguments that the user would want to modify. Considering that, I think it would be safer to insert them at the beginning (considering my assumption that the "-" arg to read from stdin needs to be last, otherwise it doesn't matter).

> 
> > Builtins with a function as base args cannot be extended
> 
> What do you mean? I tried this out with `prettier`, which uses a function to handle range formatting, and it seems to work (unless I'm misunderstanding what you want).

Sorry, I read a bit quickly and misunderstood the snippet, it should work :+1:

> Edit: `vim.list_extend` actually does return the extended list, but my example is still broken because `original_args` gets modified, so we have to make a copy of it.

Good to know :)

**Comment by Tastyep** [comment] 2021-08-13 08:34
> I think it might be better to stick to `vim.tbl_deep_extend` if possible. You can use `vim.tbl_islist` if it helps.
> 
> ```
> tbl_islist({t})                                             *vim.tbl_islist()*
>                 Tests if a Lua table can be treated as an array.
> 
>                 Empty table `{}` is assumed to be an array, unless it was
>                 created by |vim.empty_dict()| or returned as a dict-like |API|
>                 or Vimscript result, for example from |rpcrequest()| or
>                 |vim.fn|.
> 
>                 Parameters: ~
>                     {t}  Table
> 
>                 Return: ~
>                     `true` if array-like table, else `false` .
> ```

That's actually the main issue, if the entry is a list `vim.tbl_deep_extend` will overwrite it instead of extending it.

**Comment by jose-elias-alvarez** [comment] 2021-08-13 08:40
> Well, I agree that for overriding it would make more sens to provide arguments after the defaults (in theory at least), however, I don't think null-ls should specify arguments that the user would want to modify. 

This makes a lot of sense, so let's insert them at the beginning and deal with it later if any sources have issues with it. Does the `extra_args` approach make sense, then? I can review and merge a PR or work on it myself this weekend.

**Comment by Tastyep** [comment] 2021-08-13 08:49
If we use the `extra_args` approach, we need to be careful that no `args` entry is provided as `tbl_deep_extend` will overwrite them.
I can give it a try later on today if you wan’t

**Comment by kylo252** [comment] 2021-08-13 08:56
> Expected:
> 
> ```lua
> luacheck.args = { myargs + null_ls defined args }
> ```

I thought about this for a bit and I'm not sure the expected behaviour makes sense at all times. How do you turn off the defaults then? or do we support two types of args?

If it's just extending the argument list then how would you deal with something like `local default_opts = { "--set-indent=2"}` and then somebody passing `my_formatter_args = {"--set-indent=4"}`

Or did I miss something?

**Comment by Tastyep** [comment] 2021-08-13 09:04
> > Expected:
> > ```lua
> > luacheck.args = { myargs + null_ls defined args }
> > ```
> 
> I thought about this for a bit and I'm not sure the expected behaviour makes sense at all times. How do you turn off the defaults then? or do we support two types of args?
> 
> If it's just extending the argument list then how would you deal with something like `local default_opts = { "--set-indent=2"}` and then somebody passing `my_formatter_args = {"--set-indent=4"}`
> 
> Or did I miss something?

Like I said, you should never want to override the defaults, because these are useful for null-ls to work correctly.
If that's not the case, a PR should be open here to remove them.

**Comment by jose-elias-alvarez** [comment] 2021-08-13 09:20
> > > Expected:
> > > ```lua
> > > luacheck.args = { myargs + null_ls defined args }
> > > ```
> > 
> > 
> > I thought about this for a bit and I'm not sure the expected behaviour makes sense at all times. How do you turn off the defaults then? or do we support two types of args?
> > If it's just extending the argument list then how would you deal with something like `local default_opts = { "--set-indent=2"}` and then somebody passing `my_formatter_args = {"--set-indent=4"}`
> > Or did I miss something?
> 
> Like I said, you should never want to override the defaults, because these are useful for null-ls to work correctly.
> If that's not the case, a PR should be open here to remove them.

Yep! I think as long as we stick to the philosophy that the defaults represent the minimal config required to get the source to work and leave everything else to the user, this approach will work. (I'll add that to the contribution guidelines, too.)

**Comment by kylo252** [comment] 2021-08-13 09:20
> Like I said, you should never want to override the defaults, because these are useful for null-ls to work correctly.
> If that's not the case, a PR should be open here to remove them.

That makes sense, but how many of those are there? Even `stdin` should be overridable by setting `to_stdin=false`, but that seems completely ignored here:

https://github.com/jose-elias-alvarez/null-ls.nvim/blob/f8e2f9dcc171363ddf3bb024d040c9cc6864fb79/lua/null-ls/builtins/formatting.lua#L412-L416

The only thing left is basically specifying which file to use, and what the response message should like. And even though it's technically an argument to the tool, it's not an optional one at that point for null-ls.

So we could probably use a new qualifier, maybe `required_args`.

**Comment by jose-elias-alvarez** [comment] 2021-08-13 09:26
> > Like I said, you should never want to override the defaults, because these are useful for null-ls to work correctly.
> > If that's not the case, a PR should be open here to remove them.
> 
> That makes sense, but how many of those are there? Even `stdin` should be overridable by setting `to_stdin=false`, but that seems completely ignored here:
> 
> https://github.com/jose-elias-alvarez/null-ls.nvim/blob/f8e2f9dcc171363ddf3bb024d040c9cc6864fb79/lua/null-ls/builtins/formatting.lua#L412-L416
> 
> The only thing left is basically specifying which file to use, and what the response message should like. And even though it's technically an argument to the tool, it's not an optional one at that point for null-ls.
> 
> So we could probably use a new qualifier, maybe `required_args`.

I'm not sure I understand. `to_stdin` modifies how null-ls spawns the process, but that's not related to the arguments, which are passed to the process itself. 

I think it's worth remembering that built-ins are really just supposed to be a way to get things working out-of-the-box with minimal modification. Overriding / adding arguments is useful and occasionally necessary, so it makes sense to handle it, but generally speaking the goal is not to allow full customization (in those cases users should make their own sources).

**Closed** 2021-08-14 09:26 UTC
