### ISSUE TITLE
Enabling codespell causes LspInfo to show Error

### ISSUE THREAD

**Issue by LongerHV** [jose-elias-alvarez/null-ls.nvim#144] opened 2021-09-02 12:48 UTC
### FAQ

- [X] I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0-dev+206-g284199bc4

### Steps to reproduce

- Install codespell from repo (tested on Debian and Arch)
- Install Packer and null-ls
- Enable 'codespell' diagnostics
- Run :LspInfo

### Minimal init.lua to reproduce
```lua
require("packer").startup(function(use)
	use("wbthomason/packer.nvim")
	use({
		"jose-elias-alvarez/null-ls.nvim",
		requires = { "neovim/nvim-lspconfig", "nvim-lua/plenary.nvim" },
		config = function()
			local null_ls = require("null-ls")
			require("null-ls").config({ sources = { require("null-ls").builtins.diagnostics.codespell } })
			require("lspconfig")["null-ls"].setup({})
		end,
	})
end)
```

### Expected behavior

LspInfo shows up

### Actual behavior

LspInfo shows up, but throws an error:
E5108: Error executing lua Vim:E888: (NFA regexp) cannot repeat
![null_ls](https://user-images.githubusercontent.com/46924944/131845784-8ae5241c-0700-40ea-bc0e-b1aac1c317df.PNG)

### Debug log

Detected filetype: lua
1 source(s) active for this buffer:
Diagnostics: codespell

### Help

No

**Comment by jose-elias-alvarez** [comment] 2021-09-02 12:57
I've noticed this too. It's caused when a source is enabled for all filetypes, so it's most likely caused by a combination of the character `"*"` and the changes made to the `:LspInfo` window in [this commit](https://github.com/neovim/nvim-lspconfig/commit/afc4571dc8c92948131d97f9a8a1512613c5d533#diff-89ba4f73272a5b9dac754defdbb45ca9480c16a73b0623a4a217647c9a08470a). 

I don't think the lspconfig folks would want to solve this on their end, since `*` is not a valid filetype. We could either remove `"*"` from the list of filetypes shown in `:LspConfig` or change it to something else like `"all"`. What do you think?

**Comment by LongerHV** [comment] 2021-09-02 15:43
Maybe we could use an emtpy table to indicate all filetypes?

**Comment by jose-elias-alvarez** [comment] 2021-09-02 15:49
I like it. Hopefully that should play nice with their regex. I'll give it a shot and put in a fix tomorrow.

**Comment by LongerHV** [comment] 2021-09-02 15:59
Something like this should do the trick:
```
--- a/lua/null-ls/utils.lua
+++ b/lua/null-ls/utils.lua
@@ -46,6 +46,10 @@ end
 M.debug_log = require("null-ls.logger").debug

 M.filetype_matches = function(filetypes, ft)
+       -- Assume all filetypes if table is empty
+       if next(filetypes) == nil then
+               return true
+       end
     if not filetypes then
         return true
     end
```

And than in config:
```lua
local null_ls = require("null-ls")
null_ls.config({
	sources = {
		null_ls.builtins.diagnostics.codespell.with({ filetypes = { } }),
	},
})
```

**Comment by jose-elias-alvarez** [comment] 2021-09-03 03:18
Should be fixed now, thank you for the report and the suggested fix!

**Closed** 2021-09-03 03:17 UTC
Labels: bug

**Comment by AckslD** [comment] 2022-01-26 18:30
@LongerHV @jose-elias-alvarez I'm having issues with this still. For example in my config I have:
```lua
local null_ls = require('null-ls')
null_ls.setup({
    sources = {
        -- python
        null_ls.builtins.formatting.autopep8,
        null_ls.builtins.formatting.reorder_python_imports,
        -- lua
        null_ls.builtins.formatting.stylua,
        -- shell
        null_ls.builtins.code_actions.shellcheck,
        -- spell check
        null_ls.builtins.diagnostics.codespell,
        -- general
        null_ls.builtins.formatting.trim_newlines,
        null_ls.builtins.formatting.trim_whitespace,
    },
    on_attach = on_attach,
})
```
If I open a file for which I have no other LSP, eg a markdown file. Then I get the error:
```
[WARN  Wed 26 Jan 2022 07:26:45 PM CET] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:112: failed to attach buffer 1
```

Looking at the `:LspInfo` it says
```
 
 Language client log: /home/axel/.cache/nvim/lsp.log
 Detected filetype:   markdown
 
 1 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [1])
 	filetypes:       python, lua, sh
 	autostart:       false
 	root directory:  /home/axel/dev/psi/rsg/rsg_defs
 	cmd:             nvim
 
 Configured servers list: html, texlab, sumneko_lua, ccls, yamlls, jsonls, pyright, dockerls, bashls, vimls, rust_analyzer, lemminx, kotlin_language_server
```

**Comment by jose-elias-alvarez** [comment] 2022-01-27 22:24
@AckslD Could you clarify what behavior you are expecting to see? I threw your config into a minimal init file and did not see any errors when opening a Markdown file. The `codespell` source works properly and I don't see any errors when running `:LspInfo`, either.

**Comment by AckslD** [comment] 2022-01-28 08:47
Thanks a lot for checking @jose-elias-alvarez! And sorry if I this issue might be unrelated to my problem but I thought it might be caused by a similar thing.

What I'm expecting is to not see the warning:
```
[WARN  Wed 26 Jan 2022 07:26:45 PM CET] ...te/pack/packer/start/null-ls.nvim/lua/null-ls/client.lua:112: failed to attach buffer 1
```
What might be causing this warning? It seems to only happen for filetypes for which I have a source (such as `codespell`) which is configured for any filetype, while at the same time no other LSP in `lspconfig` is configured for this filetype. Could the issue be that `lspconfig` sees that no LSP has declared itself for this filetype but `null-ls` still tries to attach?

**Comment by jose-elias-alvarez** [comment] 2022-01-28 16:47
@AckslD Could you open a separate issue with a minimal reproduction? The warning indicates that something went wrong with `vim.lsp.buf_attach_client()`, which requires further debugging.

**Comment by AckslD** [comment] 2022-01-30 13:05
@jose-elias-alvarez I've been trying to reproduce with a minimal config but have not been able to. Can I open an issue anyway? You should be able to see the issue with my [config](https://gitlab.com/AckslD/config/-/tree/master/nvim).

I think the issue is that `null-ls` tries to attach to early, before the buffer is loaded. I see that in the LSP log I get the warning
```
buf_attach_client called on unloaded buffer (id: 1)
```
from [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L1224).

I opened #627 which solves the issue for me.
