### ISSUE TITLE
Expose buffer or buffer filename in `condition` callback

### ISSUE THREAD

**Issue by Mange** [jose-elias-alvarez/null-ls.nvim#718] opened 2022-02-26 21:16 UTC
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no existing ones with the same request.

### Feature description

I would like to disable `shellcheck` for env files, which are loaded with `shell` filetype, but is a very strict subset of shell scripts by convention.

One way I could do that would be to allow the buffer to be exposed in the condition, or to add a `filename_matches`. 

```lua
null_ls.builtins.diagnostics.shellcheck.with {
  condition = function(utils)
    return not utils.filename_matches("%.env$")
  end
}
```

I would still recommend exposing the actual buffer number at least, because then it would be possible to check other things that we didn't think of here. Perhaps disable a formatter on a readonly buffer, or something completely different…

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Feedback on the proposed API, and if this approach even makes sense at all. Perhaps there is some other workaround?

**Comment by Mange** [comment] 2022-02-26 21:21
For now I disable null-ls completely on these files:

```lua
  null_ls.setup {
    should_attach = function(bufnr)
      return not vim.api.nvim_buf_get_name(bufnr):match "%.env$"
    end,
    -- …
  }
```

**Comment by jose-elias-alvarez** [comment] 2022-02-27 00:34
We could pass more arguments to `condition` to support this without breaking, but the issue is that `condition` is not really buffer-specific. It tries to check upon entering a named buffer for the first time, but it disables the source completely, not just for that buffer, so I think passing the buffer number might lead to confusion.

[`runtime_condition`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#runtime_condition), which is buffer-specific, supports this via `params.bufnr`, but I don't know if that makes perfect sense for your use case. You could also check `vim.api.nvim_buf_get_name(0)` in `condition`, which should return the name of the first named buffer.

**Comment by jose-elias-alvarez** [comment] 2022-05-15 17:45
Looking at this again, I think `on_attach` is a completely valid solution. In the future null-ls will work by attaching itself to buffers vs. running unconditionally against a given set of filetypes, so the approach you've found replicates that logic nicely.

**Comment by Mange** [comment] 2022-05-16 18:54
The problem with this workaround is that it would disable all of `null-ls` on the specific buffer instead of just a particular formatter/linter. If one is using more than once on the same file, then you'd lose the other too.

**Comment by jose-elias-alvarez** [comment] 2022-05-16 19:22
You’re right, that’s a case I didn’t take into account. Let me see if I can think of anything else! In the meantime, I believe `runtime_condition` should handle this case by simply preventing the source from ever running on a given buffer, though it’s a bit clumsy.

**Comment by jose-elias-alvarez** [comment] 2022-09-02 17:04
This is going to require a larger rewrite of our architecture, so I'm going to close this issue. In the meantime, `runtime_condition` + the [`by_bufnr` helper](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/HELPERS.md#by_bufnrcallback) will handle this.

**Closed by jose-elias-alvarez** 2022-09-02 17:04 UTC
Labels: enhancement

**Comment by pcattori** [comment] 2023-01-21 20:59
@jose-elias-alvarez : could you provide an example of how to use `runtime_condition` with `by_bufnr`?

For example, to disable `diagnostics.eslint_d` for any file within `node_modules/`?
