### ISSUE TITLE
Formatting is broken on latest Neovim nightly

### ISSUE THREAD

**Issue by mrjones2014** [jose-elias-alvarez/null-ls.nvim#582] opened 2022-01-13 13:40 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

```
NVIM v0.7.0-dev+881-g4570df0b4
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by mat@Mats-Mini-337.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-4570df0/share/nvim"

Run :checkhealth for more info
```

### Operating System

macOS 12.1 Monterey

### null-ls config

```
local null_ls = require('null-ls')
local b = null_ls.builtins

local home = os.getenv('HOME')

local sources = {
  -- code actions
  b.code_actions.gitsigns,

  -- diagnostics
  b.diagnostics.eslint_d,
  b.diagnostics.luacheck,
  b.diagnostics.shellcheck.with({
    diagnostics_format = '#{m} [#{s}] [#{c}]',
  }),
  b.diagnostics.vale.with({
    args = function(params)
      return {
        '--config=' .. home .. '/.config/vale/vale.ini',
        '--no-exit',
        '--output',
        'JSON',
        '--ext',
        '.' .. vim.fn.fnamemodify(params.bufname, ':e'),
      }
    end,
  }),

  -- formatting
  b.formatting.eslint_d,
  b.formatting.prettierd.with({
    filetypes = {
      'html',
      'json',
      'javascript',
      'typescript',
      'javascriptreact',
      'typescriptreact',
      'scss',
      'css',
    },
  }),
  b.formatting.rustfmt,
  b.formatting.stylua,
  b.formatting.shfmt.with({
    filetypes = { 'sh', 'zsh', 'bash' },
    args = { '-i', '2' },
  }),
  b.formatting.fish_indent,
}

if vim.fn.filereadable('./node_modules/.bin/stylelint') > 0 then
  table.insert(
    sources,
    b.formatting.stylelint.with({
      command = './node_modules/.bin/stylelint',
    })
  )
  table.insert(
    sources,
    b.diagnostics.stylelint.with({
      command = './node_modules/.bin/stylelint',
    })
  )
end

null_ls.setup({
  sources = sources,
  on_attach = require('lsp.utils').on_attach,
  update_on_insert = true,
})
```

the `on_attach` function is defined in a separate module as:

```
local M = {}

-- Use an on_attach function to only map the following keys
-- after the language server attaches to the current buffer
function M.on_attach(client)
  vim.api.nvim_add_user_command(
    'Format',
    M.format_document,
    { desc = 'Format the document using the formatter configured in null-ls config' }
  )

  local ft = vim.bo.filetype
  if ft == 'javascript' or ft == 'typescript' or ft == 'javascriptreact' or ft == 'typescriptreact' then
    vim.api.nvim_add_user_command('OrganizeImports', M.organize_imports, { desc = 'Organize imports via tsserver' })
  end

  vim.cmd([[
    augroup fmt
      autocmd BufWritePre * Format
    augroup END
  ]])

  -- show diagnostics on hover
  vim.cmd('autocmd CursorHold * lua vim.diagnostic.open_float(nil, {focus=false, scope="cursor", border="rounded"})')

  -- setup LSP-specific keymaps
  require('keymap').apply_lsp_keymaps()

  require('lsp_signature').on_attach({
    bind = true,
    handler_opts = {
      border = 'single',
    },
    fix_pos = true,
    hint_enable = true,
    hint_prefix = '',
    padding = '',
  })

  -- Disable formatting with other LSPs because we're handling formatting via null-ls
  if client.name ~= 'null-ls' then
    client.resolved_capabilities.document_formatting = false
  end
end

function M.format_document()
  -- check if LSP is attached
  if (#vim.lsp.buf_get_clients()) < 1 then
    return
  end

  vim.lsp.buf.formatting_sync(nil, 1500)
end

function M.organize_imports()
  -- check if LSP is attached
  if (#vim.lsp.buf_get_clients()) < 1 then
    return
  end

  local ft = vim.bo.filetype
  if ft == 'javascript' or ft == 'typescript' or ft == 'javascriptreact' or ft == 'typescriptreact' then
    local params = {
      command = '_typescript.organizeImports',
      arguments = { vim.api.nvim_buf_get_name(0) },
      title = '',
    }
    vim.lsp.buf_request_sync(vim.api.nvim_get_current_buf(), 'workspace/executeCommand', params, 1500)
  end
end

return M
```

### Steps to reproduce

With the above config, since it is configured to format on write, simply run `:w`, or manually run the `:Format` command which is also defined above in the config. It does not matter if the formatting would actually result in any changes or not.

### Expected behavior

It should format the file using the configured formatter.

### Actual behavior

Formatting on save or manually executing the `:Format` command (which I've defined in my config above) results in the same issue. I get the following error in the message/command line:

`[null-ls] [WARN  08:36:44] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil`

### Debug log

```
[WARN  Thu Jan 13 08:29:56 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:29:56 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:30:16 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:30:16 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:31:40 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:31:40 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:31:45 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:31:57 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:31:57 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:15 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:15 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:15 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:165: Invalid buffer id: 12
[WARN  Thu Jan 13 08:32:20 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:20 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:20 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:165: Invalid buffer id: 14
[WARN  Thu Jan 13 08:32:41 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:41 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:41 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:165: Invalid buffer id: 15
[WARN  Thu Jan 13 08:32:46 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:46 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:32:46 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...ite/pack/packer/start/null-ls.nvim/lua/null-ls/utils.lua:165: Invalid buffer id: 17
[WARN  Thu Jan 13 08:36:38 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:36:44 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
[WARN  Thu Jan 13 08:37:34 2022] ...ack/packer/start/null-ls.nvim/lua/null-ls/formatting.lua:51: error in formatting handler: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
```

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

Seems like null-ls is using a Neovim API which has changed. I wouldn't really know where to start with helping to track that down.

**Comment by gegoune** [comment] 2022-01-13 13:43
Breaking change: https://github.com/neovim/neovim/issues/14090#issuecomment-1012005684

**Comment by mrjones2014** [comment] 2022-01-13 13:44
Ah good find!!! With that context, I think I can work on a PR to fix this.

**Comment by jose-elias-alvarez** [comment] 2022-01-13 13:50
So this diff fixes the null-ls issue:

```diff
diff --git a/lua/null-ls/client.lua b/lua/null-ls/client.lua
index 66e9de5..170f4be 100644
--- a/lua/null-ls/client.lua
+++ b/lua/null-ls/client.lua
@@ -134,6 +134,10 @@ M.get_client = function()
     return client
 end

+M.get_offset_encoding = function()
+    return client and client.offset_encoding or "utf-16"
+end
+
 M.notify_client = function(method, params)
     if not client then
         log:debug(
diff --git a/lua/null-ls/formatting.lua b/lua/null-ls/formatting.lua
index 06627e2..1b31c20 100644
--- a/lua/null-ls/formatting.lua
+++ b/lua/null-ls/formatting.lua
@@ -61,7 +61,7 @@ M.handler = function(method, original_params, handler)
         end

         local after_each = function(edits)
-            local ok, err = pcall(lsp.util.apply_text_edits, edits, temp_bufnr)
+            local ok, err = pcall(lsp.util.apply_text_edits, edits, temp_bufnr, require("client").get_offset_encoding())
             if not ok then
                 handle_err(err)
             end
```

However, as far as I can tell, the [default formatting handler](https://github.com/neovim/neovim/blob/4570df0b434f16ac9bdd71d178e297a40ef6e34a/runtime/lua/vim/lsp/handlers.lua#L240) appears to be broken because it doesn't explicitly pass the client's offset encoding when calling `apply_text_edits`. My custom formatting function works fine with the above diff, so I'll go ahead and merge it, but I think this needs to be fixed upstream as well.

**Comment by jose-elias-alvarez** [comment] 2022-01-13 14:07
> Hm, weird, I'm triggering null-ls formatting via `vim.lsp.buf.formatting_sync()` in my config and with the diff above it works for me.
> 
> I was about to put up a PR with an almost identical diff, but seems like you're already on it.

That's strange. I used the minimal init from nvim-lspconfig to test this out, and it's failing. Did you perhaps override the handler somewhere else?

I'll look into this more but plan on keeping this open until we've confirmed there's no issues upstream.

**Comment by mrjones2014** [comment] 2022-01-13 14:09
Not that I know of. In my `on_attach` I do this to ensure that `null-ls` always handles my formatting:

```lua
  -- Disable formatting with other LSPs because we're handling formatting via null-ls
  if client.name ~= 'null-ls' then
    client.resolved_capabilities.document_formatting = false
  end
```

Then my `autocmd BufWritePre` calls the `Format` command which is a user command I've defined to call a Lua function defined like so:

```lua
function M.format_document()
  -- check if LSP is attached
  if (#vim.lsp.buf_get_clients()) < 1 then
    return
  end

  vim.lsp.buf.formatting_sync(nil, 1500)
end
```

and it works for me.

**Comment by kunish** [comment] 2022-01-13 14:13
I think this feature is not yet finished, since there's no way to pass `offset_encoding` option from `vim.lsp.buf.formatting_sync` nor `vim.lsp.buf.formatting_seq_sync` into `vim.lsp.util.apply_text_edits`

https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/buf.lua#L187
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/buf.lua#L231
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L365

**Comment by mrjones2014** [comment] 2022-01-13 14:14
Ah, my mistake, it's actually not working. I tried to format a file that was already formatted so it didn't throw an error. When doing formatting that would actually result in changes, then it fails.

**Comment by mrjones2014** [comment] 2022-01-13 14:16
Is there any workaround I can use in the meantime to have `null-ls` handle the formatting directly instead of using `vim.lsp.buf.formatting_sync`?

**Comment by jose-elias-alvarez** [comment] 2022-01-13 14:19
Yep, I think this needs to be fixed in a few places upstream (I'm swamped this week and can't put in a PR). 

@mrjones2014 I think this should work for now, though I haven't tested it thoroughly:

```lua
vim.lsp.handlers["textDocument/formatting"] = function(_, res, ctx)
    if not res then
        return
    end

    local client_id = ctx.client_id
    local client = vim.lsp.get_client_by_id(client_id)
    vim.lsp.util.apply_text_edits(res, ctx.bufnr, client and client.offset_encoding or "utf-16")
end
```

**Comment by mrjones2014** [comment] 2022-01-13 14:24
Hm, I'm not sure if I'm doing something wrong but I'm getting the same error.

```
Error executing Lua callback: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: in function 'apply_text_edits'
        ...ovim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/buf.lua:187: in function 'on_choice'
        ...ovim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/buf.lua:142: in function 'select_client'
        ...ovim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/buf.lua:180: in function 'formatting_sync'
        /Users/mat/.config/nvim/lua/lsp/utils.lua:52: in function </Users/mat/.config/nvim/lua/lsp/utils.lua:46>
Press ENTER or type command to continue
```

**Comment by jose-elias-alvarez** [comment] 2022-01-13 14:31
> Hm, I'm not sure if I'm doing something wrong but I'm getting the same error.
> 
> ```
> Error executing Lua callback: ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: offset_encoding: expected string, got nil
> stack traceback:
>         [C]: in function 'error'
>         vim/shared.lua: in function 'validate'
>         ...vim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/util.lua:366: in function 'apply_text_edits'
>         ...ovim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/buf.lua:187: in function 'on_choice'
>         ...ovim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/buf.lua:142: in function 'select_client'
>         ...ovim/HEAD-4570df0/share/nvim/runtime/lua/vim/lsp/buf.lua:180: in function 'formatting_sync'
>         /Users/mat/.config/nvim/lua/lsp/utils.lua:52: in function </Users/mat/.config/nvim/lua/lsp/utils.lua:46>
> Press ENTER or type command to continue
> ```

I see, the issue is that `vim.lsp.buf.formatting_sync()` directly calls the util to apply edits. For now you could just monkey patch the runtime files or write a custom handler ([this](https://github.com/jose-elias-alvarez/dotfiles/blob/18fae3c731fe2ec917a5a68aa53420ddd8a75fd9/config/nvim/lua/lsp/init.lua#L18) is an old version from my dotfiles that also needs to pass offset encoding but should work as an example).

**Comment by mrjones2014** [comment] 2022-01-13 14:35
Thanks, I got it working with that link to your old dot files. For anyone else looking for a solution, here's how I fixed it:

```lua
function M.format_document()
  -- check if LSP is attached
  if (#vim.lsp.buf_get_clients()) < 1 then
    return
  end

  -- temporary workaround for https://github.com/jose-elias-alvarez/null-ls.nvim/issues/582
  -- switch this back once this is merged: https://github.com/neovim/neovim/pull/17075
  local bufnr = vim.api.nvim_get_current_buf()

  local selected_client
  for _, client in ipairs(vim.lsp.get_active_clients()) do
    if client.name == 'null-ls' then
      selected_client = client
    end
  end

  if not selected_client then
    return
  end

  local params = vim.lsp.util.make_formatting_params()
  local result, err = selected_client.request_sync('textDocument/formatting', params, 5000, bufnr)
  if err then
    local err_msg = type(err) == 'string' and err or err.message
    vim.notify('global.lsp.formatting: ' .. err_msg, vim.log.levels.WARN)
    return
  end

  if result and result.result then
    vim.lsp.util.apply_text_edits(result.result, bufnr, require('null-ls.client').get_offset_encoding())
  end
  -- vim.lsp.buf.formatting_sync(nil, 1500)
end
```

**Comment by mjlbach** [comment] 2022-01-13 14:37
y'all, it's going to be fixed in 5. Just roll back to the last commit until tests pass...

**Comment by mjlbach** [comment] 2022-01-13 15:02
FYI the PR was merged, so unless the "client" object of null-ls is missing an offset_encoding param this should be closed.

**Comment by jose-elias-alvarez** [comment] 2022-01-13 16:58
> FYI the PR was merged, so unless the "client" object of null-ls is missing an offset_encoding param this should be closed.

Thanks! I think we've solved it on our end so I'm going to close this.

**Closed by jose-elias-alvarez** 2022-01-13 16:58 UTC
Labels: bug
