### ISSUE TITLE
Error: Oneshot channel can only send once #302 

### ISSUE THREAD

**Issue by ahhshm** [jose-elias-alvarez/null-ls.nvim#553] opened 2022-01-06 17:57 UTC
### FAQ

- [X] I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.0 Build type: Release LuaJIT 2.0.5 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### null-ls config

```lua
local null_ls_status_ok, null_ls = pcall(require, "null-ls")
if not null_ls_status_ok then
	return
end


local formatting = null_ls.builtins.formatting
local diagnostics = null_ls.builtins.diagnostics
local code_actions = null_ls.builtins.code_actions

null_ls.setup({
	debug = false,
	sources = {
		formatting.prettier,
		formatting.black.with({ extra_args = { "--fast" } }),
		formatting.stylua,
		diagnostics.eslint,
		code_actions.eslint,
	},
	on_attach = function(client)
		if client.resolved_capabilities.document_formatting then
			vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
		end
	end,
})

```

### Steps to reproduce

I don't think this error could be reproduced because I don't get it always. I face this error mostly when I'm editing javascript and typescript codes. I use null-ls to auto-format my codes using `prettier`.

### Expected behavior

Format and save the file without any error.

### Actual behavior

I get this error:
```
Error executing vim.schedule lua callback: .../packer/start/plenary.nvim/lua/plenary/async/control.lua:111:
Oneshot channel can only send once
stack traceback:
        [C]: in function 'assert'
        .../packer/start/plenary.nvim/lua/plenary/async/control.lua:111: in function 'done'
        ...t/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:238: in function 'handler'
        ...site/pack/packer/start/null-ls.nvim/lua/null-ls/loop.lua:67: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

After I press Enter multiple times to dismiss the error, wired things happen such as some parts of my code duplicates and I can't use noevim and I have to restart it. formatting js files always takes too long. sometimes I get a timeout error and sometimes the above error. I don't know why prettier is so slow. formatting other files with other formatting is much faster.

### Debug log

the logs aren't relevant to the error

### Help

No

**Comment by jose-elias-alvarez** [comment] 2022-01-06 18:06
Duplicate of #483. This seems to be an issue with slow-running sources in general, and vanilla `prettier` is, as you noted, very slow. You could try using [`prettierd`](https://github.com/fsouza/prettierd), which will both prevent the error and provide a much better experience.

**Closed by jose-elias-alvarez** 2022-01-06 18:06 UTC
Labels: bug
