### ISSUE TITLE
Please provide documentation to configure generic (non-builtin) linters and formatters

### ISSUE THREAD

**Issue by krishnakumarg1984** [jose-elias-alvarez/null-ls.nvim#508] opened 2021-12-28 18:38 UTC
First of all, thanks a lot for `null-ls`. This is indeed such an awesome plugin that I am migrating my previous linting and formatting setup from ALE during this winter break.

The built-in diagnostics and formatting for C++ works well. However, I'd like to know how to configure a few other useful linters and formatters such as:

- [flawfinder](https://github.com/david-a-wheeler/flawfinder)
- [cpplint](https://github.com/google/styleguide/tree/gh-pages/cpplint)
- [clang-tidy](https://clang.llvm.org/extra/clang-tidy/)

 for C++ filetype. A wiki entry in the project's documentation to configure generic linters and formatters shall be much appreciated.

**Comment by jose-elias-alvarez** [comment] 2021-12-29 16:10
The documentation is a work in progress (see #364). At the moment, the best way to add a new source is to look at existing built-ins and modify them as necessary. #69 contains an implementation for clang-tidy that may work as a starting point.

**Comment by krishnakumarg1984** [comment] 2022-01-21 15:44
Okay. Thank you.  It would be good to have `clang-tidy` to be available in the official supported list of linters at some point in the future

**Comment by jose-elias-alvarez** [comment] 2022-09-06 19:44
This is essentially a duplicate of #364, so I'm closing it in favor of that issue. I'm still open to PRs to improve the documentation situation, though I'd ideally like to make some changes to the core null-ls source API before doing it myself.

**Closed by jose-elias-alvarez** 2022-09-06 19:44 UTC
